src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
Azure_Subscription_Config_Azure_Security_Center control is Passing even though we have mis-configured ASC policies if SecurityCenterConfigVersion is not latest.
=> Fix for: Azure_Subscription_Config_Azure_Security_Center control passing even though Sub has mis-configured ASC policies 

src/AzSK/Framework/Helpers/Helpers.ps1
</br>
I had added Force switch for Set-AzureRmResourceGroup as it was present for Set-AzureRmResource. But Set-AzureRmResourceGroup doesn't support Force switch.
=> Removing Force switch as Set-AzureRmResourceGroup doesn't support 

src/AzSK/Framework/Configurations/SVT/Services/Automation.json, src/AzSK/Framework/Core/SVT/AzSKCfg/AzSKCfg.ps1
</br>
Recommendation for the control "Azure_Automation_DP_Use_Encrypted_Variables" is modified. The -Force parameter has been removed from the Remove-AzureRmAutomationVariable command in the recommendation as it was throwing error. It works fine when the parameter is not used.
=> [Baseline Control validation] Recommendation changed : -Force parameter doesn't work.

src/AzSK/Framework/Abstracts/SVTCommandBase.ps1
Update the attestation error message to make a note of clearing the Azure cache on elevating the user permissions.
</br>
Updated the attestation error message to make sure if the Azure cache was cleared after elevating the user permissions.
=> Attestation error message update

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
</br>
A person cannot be a co-admin if he/she's not already an Owner on the sub - hence, removed the selection criteria of 'CoAdministrator' - in order to get each user just ONCE.
=> Count Admin/Owner distinctly

src/AzSK/Framework/Core/SVT/Services/AppService.ps1
</br>
Azure_AppService_DP_Use_CNAME_With_SSL control logic was incorrectly calculating number of custom domains having SSL disabled.
=> Bug fix for control Azure_AppService_DP_Use_CNAME_With_SSL

src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1
</br>
SVT extension is not respected when multiple resource instances are used. After the first resource is scanned, it is unable to fetch the extended control method as it was already loaded in the first resource scan.
=> SVT extension is not respected when multiple resource instances are used.

src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1
</br>
1. In case of single result being returned for resources with baseline controls, the array was being set to object type, hence, resulting in exception when trying to add more objects to it.
Fixed that by making sure the array is not implicitly type-casted to object!
2. Renamed variable to improve readability/understandability.
=> Fixed type casting

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
</br>
1. Added CoAdministrator role to the count, since they can be added independent of the Owner privilege.
2. Added "RoleDefinitionName" to the output logs for clarity of the role assignment.
=> Logic update for Azure_Subscription_AuthZ_Limit_Admin_Owner_Count

src/AzSK/Framework/Abstracts/AzSKRoot.ps1, src/AzSK/Framework/Core/SVT/Services/NotificationHub.ps1, src/AzSK/Framework/Core/SVT/Services/ServiceBus.ps1
</br>
- Fixed the logic for the control Azure_NotificationHub_AuthZ_Dont_Use_Manage_Access_Permission
- Fixed the logic for the control Azure_ServiceBus_AuthZ_Dont_Use_Policies_At_SB_Namespace
- Bug fix for [P2 bug](https://microsoftit.visualstudio.com/OneITVSO/_workitems/edit/4209791/) regarding error handling when running scans with invalid subscription or tenant.
=> Bug fixes for controls and one P2 bug

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetupAzureRm.ps1, src/OSSConfiguration/RunbookCoreSetupAzureRm.ps1
</br>
Currently we check for the base version of RM.Profile  if it is greater than the default, it then only installs the RM dependencies, which is blocking the users trying to install older version of AzSK as they would have newer profile version.
=> Changes for mix up scenario to install RM dependencies 

src/AzSK/Framework/Core/SVT/Services/AppService.ps1, src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1, src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1
</br>
Happened in Contoso Org policy. Even when no baseline or preview baseline controls are defined, on passing the upbc/ubc switch, all controls would get scanned which should not be the case. That has now been handled appropriately.
Also fixed [bug](https://microsoftit.visualstudio.com/OneITVSO/_workitems/edit/4375060) regarding App Service.
=> Fixing framework behaviour when no baseline/preview baseline controls are defined

src/AzSK/Framework/Core/SVT/Services/AppService.ps1
1. Azure_AppService_AuthN_Use_AAD_for_Client_AuthN
2. Azure_AppService_DP_Dont_Allow_HTTP_Access_Fn
</br>
=> Fixed Controls error when AppService is Stopped -

src/AzSK/Framework/Core/SVT/Services/Storage.ps1
Disabling the control 'Azure_Storage_AuthN_Dont_Allow_Anonymous' for Data Lake Storage Gen2 resources with hierarchical namespace accounts enabled as blob storage is not currently supported.
=> Disabling anonymous storage access for ADLS Gen2 with HNS enabled. - Updated

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
I have updated the whitelist of variables to skipped as a part of the scan of the control 'Azure_Automation_DP_Use_Encrypted_Variables'. This whitelist applies only to the CA present in AzSKRG.
=> Whitelisting AzSKContinuousAssurance variables

src/AzSK/Framework/Core/SVT/Services/EventHub.ps1
</br>
Removed extra code that caused the control to result in 'Verify' state overwriting the correct state
=> [Bug]: 'Azure_EventHub_AuthZ_Use_Min_Permissions_Access_Policies' always goes in 'Verify'

src/AzSK.Framework/Abstracts/SVTBase.ps1, src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1
</br>
Previously controls that reported 'Error' state could be attested. With these changes in place attestation of controls in 'Error' state would not be allowed.
Further if someone had previously attested the controls that were actually in 'Error' state, there attestation would expire.
=> [Bug]: Controls in 'Error' status should not be allowed for attestation

src/AzSK/Framework/Configurations/SVT/ControlSettings.json, src/AzSK/Framework/Configurations/SVT/Services/KeyVault.json, src/AzSK/Framework/Core/SVT/Services/KeyVault.ps1
</br>
Performance issue in key vault controls that used FetchAllEnabledSecretsWithVersions and FetchAllEnabledKeysWithVersions has been fixed, and a new control has been added to check if a key or secret has too many versions.
=> new control for key vault and perf bug fix

src/AzSK/Framework/Configurations/SVT/ControlSettings.json, src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
</br>
With this capability, now policy owners will be able to whitelist resource groups by providing RG names or regular expressions under _WhitelistedResourceGroups_ in the ControlSettings.json, with which RGs can be matched, in order to exempt them from tagging compliance.
=> Whitelisting RGs in tagging compliance

src/AzSK.Framework/Abstracts/CommandBase.ps1, src/AzSK.Framework/Helpers/CommandHelper.ps1, src/AzSK.Framework/Helpers/ConfigurationHelper.ps1, src/AzSK.Framework/Models/CommandDetails.ps1
Added ability for IOP/UOP/GOP commands to 'ignore' or avoid blocking without needing to remove the AzSKRG org-policy tag.
=> Bug fix: Removed IOP/UOP/GOP commands dependency on org-policy tag.

src/AzSK/Framework/Configurations/SubscriptionSecurity/SecurityCenter.json, src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1, src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1, src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenterStatus.ps1, src/AzSK/SubscriptionSecurity/SecurityCenter.ps1
</br>
This PR contains the following:
1. More mandatory ASC default initiative policies will now be checked via control 'Azure_Subscription_Config_Azure_Security_Center'.
2. Many optional ASC policies will now be checked for telemetry purpose.
3. Set-AzSKAzureSecurityCenterPolicies will now have an additional switch to fix the missing/misconfigured optional policies.
=> Enforcing mandatory and optional ASC default initiative policies.

src/AzSK/Framework/Configurations/SubscriptionSecurity/SecurityCenter.json, src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1, src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1, src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenterStatus.ps1, src/AzSK/SubscriptionSecurity/SecurityCenter.ps1
</br>
This PR contains the following:
1. More mandatory ASC default initiative policies will now be checked via control 'Azure_Subscription_Config_Azure_Security_Center'.
2. Many optional ASC policies will now be checked for telemetry purpose.
3. Set-AzSKAzureSecurityCenterPolicies will now have an additional switch to fix the missing/misconfigured optional policies.
=> Adding mandatory and optional ASC default initiative policies.

src/AzSK/Framework/Configurations/SVT/Services/Storage.json, src/AzSK/Framework/Core/SVT/Services/Storage.ps1
</br>
Disabling the control 'Azure_Storage_AuthN_Dont_Allow_Anonymous' for FileShare type available in Premium storage account as blobs and containers are not supported in it, which renders API inaccessible causing control to error out.
=> Fixed anon authN storage control in fileshare type

src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1, src/AzSK/SubscriptionSecurity/SecurityCenter.ps1
</br>
This PR contains the following changes:
1. Set-AzSKAzureSecurityCenterPolicies paramater name "OptionalPolicies" has been renamed to "EnableOptionalPolicies" - although the older name will still be prevalent as alias.
2. In case of duplicate ASC default initiatives, polices with stronger effect ultimately win across the scope (in this case, the scope is subscription.). Before we were checking for policy effect only across ASC default initiative (maintained by AzSK). So in case where we need a policy X effect to be 'Disabled' across the subscription, we need to ensure it is 'disabled' across all the ASC assignments. Here we check for the effect across all assignments (GET scenario).
3. For SET scenario, we will be updating 'ASC default initiative' (maintained by AzSK) as per …
=> Resolving the policy effect check for duplicate ASC assignments.

src/AzSK/Framework/Configurations/FeatureFlighting.json, src/AzSK/Framework/Configurations/SVT/ControlSettings.json, src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1
</br>
Policy names keep changing in ASC. So instead of comparison using names, now we will compare using assessmentKey which is like the policy ID for each ASC Policy.
=> assessmentKey comparison for ASC VM Controls

src/AzSK.Framework/Listeners/RemoteReports/RemoteReportsListener.ps1, src/AzSK.Framework/Models/Common/ResourceInventory.ps1
</br>
If no resource is present in the subscription, GSS errors out in CA mode.
Added a null-check for resource count in the sub.
=> fix for gss erroring out in CA if no resource found in the sub.

src/AzSK.Framework/Abstracts/SVTCommandBase.ps1
Fix for GAI -AttestationInfo  and GACS 'You cannot call a method on a null-valued expression.' error
=> bug fix: AttestationInfo unable to fetch attestation data and GACS

src/AzSK.Framework/Abstracts/SVTBase.ps1, src/AzSK/Framework/Configurations/FeatureFlighting.json, src/AzSK/Framework/Configurations/SVT/ControlSettings.json, src/AzSK/Framework/Configurations/SVT/Services/AppService.json, src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1
The changes are:
1) Added feature flight control to enable/disable sending of VM's ASC settings in metadata.
2) Added a property in control settings file to enable sending of resource metadata to API for allowed resource types
=> VM ASC metadata capture control and resourcetype control for sending metadata

src/AzSK/Framework/Configurations/FeatureFlighting.json, src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1, src/AzSK/PIM/PIM.ps1
1)Check for CA SPN name expression removed to by pass force certificate creation in case an AD App with name not according to AzSK SP naming convention is used in automation account run as connection
2)Added previous parameter name  for PrincipalNames in alias
=> Changes to remove check for CA SPN formatting in central mode

src/AzSK.Framework/Abstracts/CommandBase.ps1, src/AzSK/Framework/Core/PIM/PIMScript.ps1, src/AzSK/PIM/PIM.ps1
</br>
Addition of management group as scope for PIM commands(getpim and setpim).
Currently ConfigureRoleSettings option is only scoped to subscription/resourcegroup/resource level
=> Changes for adding Management Group as scope for PIM commands

src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json
I have fixed issue for control "Azure_VirtualMachine_NetSec_Justify_PublicIPs"
There are some properties which are unnecessary added into the configuration file, so I have removed those properties and keeps only required properties.
=> Removed unnecessary properties for VM public ip control

src/AzSK.AzureDevOps/Framework/Abstracts/ADOSVTBase.ps1, src/AzSK.AzureDevOps/Framework/Abstracts/ServicesSecurityStatus.ps1, src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Build.ps1, src/AzSK.AzureDevOps/Framework/Core/SVT/SVTResourceResolver.ps1, src/AzSK.Framework/Abstracts/CommandBase.ps1, src/AzSK.Framework/Abstracts/SVTBase.ps1, src/AzSK.Framework/Helpers/ConfigOverride.ps1, src/AzSK.Framework/Helpers/ConfigurationHelper.ps1, src/AzSK.Framework/Helpers/LogAnalyticsHelper.ps1
</br>
1) Perf fixes (to sync w. AzSK 4.12.x). 
- Org policy caching. 
- Resolved SVTConfig overlay. 
- CheckBaselineControls (removed subscriptionList as n/a for ADO).
- Added NotExtendedType hash table for perf.
2) Type load bug from AzSK 
- If the type 'Build' is extended...Build-Release-Build sequence would not apply BuildExt to 2nd build object.)
3) Turned off 'IsLargeScanAllowed' check (too early). Need to revisit later.
4) Removed NA feature flag from LA helper/event sender.
5) Cached security config in Build object.
=> Various perf and bug fixes (perf ~AzSK 4.12.x)

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.ServiceConnection.ps1, src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.User.ps1
</br>
This PR is for fixing issues related to Datetime.split is not supported in Linux ( Workitem-6230844)
Used New-Timespan utility wherever we are calculating the **timespan** between two dates 
- [ y] I have read the instructions mentioned in [Contribute to Code](/Contributing.md).
- [ y] I have read and understood the criteria described under [submitting changes](/Contributing.md#submitting-changes). 
- [y ] The title of the PR clearly describes the intent of the PR.
- [ y] This PR does not introduce any breaking changes to the code.
=> Bug fixes for workitem-6230844 

src/AzSK.ADO/ContinuousAssurance/ContinuousAssurance.ps1, src/AzSK.ADO/Framework/Core/ContinuousAssurance/CAAutomation.ps1
</br>
Added support for the following to facilitate faster dev-test for UCA:
> [string] $RsrcTimeStamp 
> [string] $ContainerImageName, 
> [string] $ModuleEnv, 
> [bool] $UseDevTestImage, 
> [int] $TriggerNextScanInMin
e.g., one can now run stuff like:
> $rgName='mpadorg'
> $extCmd = '-ubc'
> $nextScanMin = 2
> $imgName = 'mprabhu11/adosecurityscan'
> $devTest = $true
> $timeStamp= '200830092449'
> uca -sub $s4 -rg $rgName -oz $orgName -pn $newProj -ex $extCmd -rsrctimestamp $timeStamp -triggerNextScanInMin $nextScanMin -ContainerImageName $imgName -UseDevTestImage $true
=> DevTest support in UCA

src/AzSK.ADO/Framework/Abstracts/ADOSVTCommandBase.ps1, src/AzSK.ADO/Framework/Configurations/SVT/ControlSettings.json, src/AzSK.ADO/Framework/Helpers/ContextHelper.ps1, src/AzSK.ADO/Framework/Models/AzSKSettings.ps1, src/AzSK.Framework/Helpers/ConfigurationHelper.ps1
</br>
- Added support to determine actual user from PAT (during context initialization). This allows us to do attestation using PATToken.
- Handling of situations when SCMD cannot be downloaded (incorrect org policy URL, policy-repo doesn't exist, no permission, etc.). We revert back to local policy gracefully.
- Include ADO PATToken regex for creds-in-pipelines control
=> Getting user from PAT. PAT regex. Etc.

src/AzSK.ADO/Framework/Abstracts/ADOSVTBase.ps1, src/AzSK.ADO/Framework/Abstracts/ADOSVTCommandBase.ps1, src/AzSK.ADO/Framework/BugLog/AutoBugLog.ps1, src/AzSK.ADO/Framework/BugLog/AutoCloseBugManager.ps1, src/AzSK.ADO/Framework/Core/SVT/SVTControlAttestation.ps1, src/AzSK.ADO/Framework/Helpers/Constants.ps1, src/AzSK.ADO/Framework/Managers/ControlStateExtension.ps1, src/AzSK.Framework/Helpers/Helpers.ps1, src/AzSK.Framework/Models/RemoteReports/ComplianceStateModel.ps1, src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1
Change to use similar helper for bug log.
</br>
Changed attestation to use shorter (12-hex-char) hashes. 
Added helper function in auto-bug-log for the same. (It was computing full hash string and using first 12 chars from that.)
Other clean-up.
=> Change to use shorter hashlen for attestation.

src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Build.json, src/AzSK.ADO/Framework/Configurations/SVT/ControlSettings.json, src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1, src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Organization.ps1, src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.User.ps1
</br>
Items addressed
1) Removed unnecessary log like "Failed/Verify" from ADO_User_AuthZ_Review_Token_Expiration
2) Segregated full access and others for ADO_User_AuthZ_PAT_Min_Access
3) Split display of "never" active v. not-active-for-N-days for ADO_Organization_AuthZ_Review_Inactive_Users
4) Added control at build/release level to limit AuthZ scope (=> attest if you need to still use x-project scope)
=> [ADO] changes related to org, build and users for sprint2010

src/AzSK.ADO/AzSKADOInfo/AzSKADOInfo.ps1, src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1, src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Organization.ps1, src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Project.ps1, src/AzSK.ADO/Framework/Core/SVT/SVTResourceResolver.ps1
</br>
1. ADO_Organization_AuthN_Use_ALT_Accounts_For_Admin - control will now fail if atleast one non SC-ALT account is found. Printing count for both alt and non-alt entities. Also, skipping PCSA from alt account check
2. ADO_Project_AuthN_Use_ALT_Accounts_For_Admin - control will now fail if atleast one non SC-ALT account is found. Printing count for both alt and non-alt entities. 
3. ADO_Organization_SI_Review_Installed_Extensions - aded counted for trusted vs non-trusted extensions and also the criteria for trusting a publisher.
4. GADI will now work with org-policy based control info if PolicyProject flag is used.
5. ADO_Build_SI_Disable_Task_Group_Edit_Permission control will not error out for YAML pipelines.
=> [ADO] admin control updates plus edit task grp control for yaml pipelines plus gadi policy project
