src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1
src/OSSConfiguration/ControlSettings.json

Added manual condition if unable to fetch ASC Settings data for a VM.
Added Antimalware control as baseline control in OSS config file.

Bug fix for VM Missing Patches Control and Missing OS Vulnerabilities Control 

---

src/AzSK/Framework/Listeners/UserReports/WriteSummaryFile.ps1

@sbyna-msft @VishalHaibatpure @ShrutiBhambhani @ganesh-msft 
Kindly review this PR.

fix for displaying resource Id in the CSV logs

---

src/AzSK/Framework/Listeners/Webhook/WebhookOutput.ps1

changes for multiple calls to single call in webhook

changes for multiple calls to single call in webhook

---

src/AzSK/Framework/Configurations/SVT/Services/Storage.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Listeners/OMS/OMSOutput.ps1
src/OSSConfiguration/ControlSettings.json

- Removed encrypt at rest control for Storage as it's by default behaviour 
- Changing message type for error while pushing data to OMS

Removed encrypt at rest control for Storage as it's by default behaviour, changed the message type  for OMS data pushing error 

---

src/AzSK/Framework/Configurations/SVT/Services/CDN.json
src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1

1. Add dummy function to check if control is attestable.
2. Added filter for blacklisted attestation
3. Corrected "InvalidAttestationStates" value template in CDN.json

blacklisted attestation changes

---

README.md

Added link to DevOpsKit Documentation in README.

Update README.md with link to DevOpsKit Documentation for easy reference

---

src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1

fixed InvalidAttestationStates null error

---

src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1

keep willfixlater when IsControlInGrace is true

---

src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1

check if ValidAttestationState is null

---

src/AzSK/Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1

Changed firstFailedOn to FirstScannedOn for caculating grace period

---

src/AzSK/Framework/Configurations/SVT/Services/AnalysisServices.json
src/AzSK/Framework/Configurations/SVT/Services/Batch.json
src/AzSK/Framework/Configurations/SVT/Services/BotService.json
src/AzSK/Framework/Configurations/SVT/Services/ServiceFabric.json

</br>
As these controls were referring storage encryption at rest which is be default enabled now so making these controls as informational.
Azure_Batch_DP_Encrypt_Linked_Storage
Azure_BotService_DP_Encrypt_At_Rest
Azure_AnalysisServices_DP_Encrypt_At_Rest
Azure_ServiceFabric_DP_Enable_Encryption_Stg_Acc_Store_VHD

Changed below controls as informational

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json

</br>
Fix for below metric alert control as they were failing due to schema change -
Azure_Storage_Audit_Issue_Alert_AuthN_Req
Azure_Batch_Audit_Enable_Metric_Alert
Azure_StreamAnalytics_Audit_Issue_Alert_Runtime_Errors_Failed_Functions

Fix for metric alert control

---

src/AzSK/Framework/Abstracts/SVTBase.ps1

Fixed compile time error

---

src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1

Remove redundant validattestationstate calculation from bulk attestation

---

.vscode/launch.json
src/AzSK/AzSKStaging.psd1
src/AzSK/Framework/Configurations/AzSk.json
src/AzSK/Framework/Listeners/RemoteReports/AIOrgTelemetry.ps1
src/AzSK/Framework/Models/AzSKConfig.ps1

renamed the file

---

src/AzSK/Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Abstracts/SVTCommandBase.ps1

fixed minor issues

---

src/AzSK/Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1

minor changes related to storagereportdata

---

src/AzSK/Framework/Helpers/ComplianceReportHelper.ps1
src/AzSK/Framework/Helpers/ResourceHelper.ps1

minor fixes

---

src/AzSK/Framework/Abstracts/CommandBase.ps1
src/AzSK/Framework/Abstracts/ListenerBase.ps1
src/AzSK/Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/Framework/Helpers/ConfigOverride.ps1
src/AzSK/Framework/Models/Enums.ps1
src/AzSK/PolicySetup/PolicySetup.ps1

Bug fixes for control enhancement feature

---

src/OSSConfiguration/ARMControls.json

</br>
Removing Storage controls from ARMTemplateChecker that was removed from AzSK

Removing Storage controls that was removed from AzSK

---

src/AzSK/Framework/Abstracts/SVTBase.ps1

Minor change in Grace Calculation

---

src/AzSK/Framework/Helpers/WebRequestHelper.ps1

Added SuppressedException: If user runs GSS Scan with reader access only on RG

---

src/AzSK/Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Helpers/OMSHelper.ps1
src/AzSK/Framework/Listeners/OMS/OMSOutput.ps1
src/AzSK/Framework/Listeners/RemoteReports/AIOrgTelemetry.ps1

OrgPolicyName addition in OMS and AI telemetry

---

src/AzSK/Framework/Helpers/Helpers.ps1

</br>
Added try catch for adding tag(s)
Printing error while adding

Added try catch for Adding tag

---

src/AzSK/Framework/Helpers/ComplianceReportHelper.ps1

# Resolve child control duplicate issue

---

src/AzSK/Framework/Abstracts/CommandBase.ps1

Message update for OSS mixup

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

CA UI msg change

---

src/AzSK/Framework/Configurations/SVT/Services/ContainerInstances.json

Modifed Continer SVT json text.

---

src/AzSK/Framework/Configurations/SVT/Services/BotService.json

changes for new control

---

src/AzSK/Framework/Abstracts/CommandBase.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/Framework/Listeners/OMS/OMSOutput.ps1
src/AzSK/PolicySetup/PolicySetup.ps1

Fixes for OMS/OSS mixup message/Org Policy Update command

---

src/AzSK/AzSK.pssproj
src/AzSK/Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1
src/AzSK/Framework/Core/AzSKInfo/PersistedStateInfo.ps1
src/AzSK/Framework/Framework.ps1
src/AzSK/Framework/Listeners/UserReports/WriteSummaryFile.ps1
src/AzSK/Framework/Models/RemoteReports/CsvOutputModel.ps1

Users tashuk featureclone

---

src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/Framework/Listeners/RemoteReports/AIOrgTelemetry.ps1
src/AzSK/Framework/Listeners/RemoteReports/UsageTelemetry.ps1
src/AzSK/Framework/Models/AzSKConfig.ps1
src/AzSK/PolicySetup/PolicySetup.ps1

Bug fixes for anonymous telemetry, latest version api change

---

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/AzSK/Framework/Helpers/ComplianceReportHelper.ps1
src/OSSConfiguration/RunbookScanAgent.ps1

Handled ResourceId not found exception + Exclude RBAC controls from CA

---

src/AzSK/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

Default names validation in CA

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Models/SubscriptionSecurity/SubscriptionRBAC.ps1

PIM API Integration for new control

---

src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1
src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1
src/AzSK/Framework/Helpers/ConfigurationHelper.ps1
src/AzSK/Framework/Helpers/Constants.ps1
src/AzSK/Framework/Helpers/Helpers.ps1
src/AzSK/Framework/Managers/ConfigurationManager.ps1
src/AzSK/Framework/Models/SVT/SVTConfig.ps1

Extension model related changes

---

src/AzSK/Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Listeners/RemoteReports/AIOrgTelemetry.ps1

User tashuk sprint1807

---

src/AzSK/Framework/Models/AzSKSettings.ps1

Code to clean up AzSDK on local machine for Local settings folder

---

src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/Framework/Helpers/ConfigurationHelper.ps1
src/AzSK/Framework/Helpers/Constants.ps1
src/AzSK/Framework/Listeners/ListenerHelper.ps1
src/AzSK/Framework/Managers/ConfigurationManager.ps1

Add function to extend listeners

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/Services/Storage.ps1

- Added "StorageV2" kind in Storage Kind mapping
- Added "Zone-redundant storage" in Storage diagnostics mapping
</br>

Added mapping for StorageV2 in ControlSettings.json

---

src/AzSK/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/Continuous_Assurance_Resource_Creation_Runbook.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/Continuous_Assurance_ScanOnTrigger_Runbook.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/AzSK/Framework/Configurations/SubscriptionSecurity/Subscription.InsARMAlerts.json
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/Alerts.ps1
src/AzSK/Framework/Helpers/Constants.ps1

Changes on success-full happy path run

---

src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1
src/AzSK/Framework/Helpers/Constants.ps1

1) Used helper methods and constants for API call
2) Telemetry call moved to end of command execution .
3) Removed existing control that checked if PIM is enabled for a subscription .

PIM API Integration changes

---

src/AzSK/AzSK.psm1
src/AzSK/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK/Framework/Abstracts/CommandBase.ps1
src/AzSK/Framework/Abstracts/ComplianceBase.ps1
src/AzSK/Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Configurations/AzSk.json
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1
src/AzSK/Framework/Core/AzSKInfo/PersistedStateInfo.ps1
src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1
src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1
src/AzSK/Framework/Framework.ps1
src/AzSK/Framework/Helpers/ComplianceReportHelper.ps1
src/AzSK/Framework/Helpers/Constants.ps1
src/AzSK/Framework/Helpers/Helpers.ps1
src/AzSK/Framework/Helpers/OMSHelper.ps1
src/AzSK/Framework/Helpers/ResourceHelper.ps1
src/AzSK/Framework/Helpers/UserSubscriptionDataHelper.ps1
src/AzSK/Framework/Helpers/WebRequestHelper.ps1
src/AzSK/Framework/Listeners/CA/WriteCAStatus.ps1
src/AzSK/Framework/Listeners/RemoteReports/AIOrgTelemetry.ps1
src/AzSK/Framework/Listeners/RemoteReports/RemoteReportsListener.ps1
src/AzSK/Framework/Listeners/UserReports/WriteSummaryFile.ps1
src/AzSK/Framework/Models/AzSKConfig.ps1
src/AzSK/Framework/Models/AzSKSettings.ps1
src/AzSK/Framework/Models/Common/ResourceInventory.ps1
src/AzSK/Framework/Models/RemoteReports/ComplianceStateModel.ps1
src/AzSK/Framework/Models/SVT/SVTEvent.ps1

LocalComplianceState

---

src/AzSK/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK/Framework/Abstracts/ComplianceBase.ps1
src/AzSK/Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1
src/AzSK/Framework/Core/AzSKInfo/PersistedStateInfo.ps1
src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1
src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1
src/AzSK/Framework/Helpers/ComplianceReportHelper.ps1
src/AzSK/Framework/Listeners/CA/WriteCAStatus.ps1
src/AzSK/SVT/SVT.ps1

Commented Reg listner

---

src/AzSK/Framework/Configurations/SVT/Services/NotificationHub.json
src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json

</br>
Updates to the recommendations for some of the Subscription core and Notification Hub controls.

Users/ganesh msft/recommfix

---

src/AzSK/Framework/Configurations/ContinuousAssurance/Continuous_Assurance_ScanOnTrigger_Runbook.ps1
src/AzSK/Framework/Configurations/SubscriptionSecurity/Subscription.InsARMAlerts.json
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/Alerts.ps1

changes for action group constant name

---

src/AzSK/Framework/Helpers/OMSHelper.ps1
src/AzSK/Framework/Listeners/OMS/OMSOutput.ps1

oms warning fix v2

---

src/AzSK/Framework/Configurations/SubscriptionSecurity/Subscription.InsARMAlerts.json
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

bom character issue

---

src/AzSK/Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1
src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1
src/AzSK/Framework/Listeners/RemoteReports/RemoteReportsListener.ps1
src/AzSK/Framework/Managers/ControlStateExtension.ps1

attestation concurrency bug fix

---

src/AzSK/Framework/Abstracts/SVTBase.ps1

storage controls issue due to disabled control

---

src/AzSK/Framework/Configurations/SVT/Services/DataFactory.json

Adding data factory V2 controls

---

src/AzSK/Framework/Abstracts/SVTBase.ps1

Minor fix for setting IsControlInGrace

---

src/AzSK/Framework/Helpers/ConfigOverride.ps1

Fixed CSS command issue

---

src/AzSK/Framework/Listeners/OMS/OMSOutput.ps1

Disabled OMS inventory call

---

src/OSSConfiguration/RunbookScanAgent.ps1

changes for oss config runbook scan agent

---

src/AzSK/Framework/Configurations/SVT/Services/AppService.json

Removed hard coded Grace Expiry Date from control

---

src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1

Minor bug fix

---

src/AzSK/Framework/Listeners/RemoteReports/RemoteReportsListener.ps1

RBAC call bug fix

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

Removed resource lock check in CA RG

---

src/AzSK/Framework/Helpers/Helpers.ps1

Users tashuk sprint1808

---

src/AzSK/AzSK.psm1
src/AzSK/AzSKStaging.psd1
src/AzSK/Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/Continuous_Assurance_Runbook.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/Continuous_Assurance_ScanOnTrigger_Runbook.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/AzSK/Framework/Configurations/SubscriptionSecurity/Subscription.ARMPolicies.json
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/SVT/Services/Automation.ps1
src/AzSK/Framework/Core/SVT/Services/DataLakeStore.ps1
src/OSSConfiguration/RunbookScanAgent.ps1

AzureRm 6.5.0 --> 6.6.0

---

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/AzSK/Framework/Configurations/SVT/Services/BotService.json
src/AzSK/Framework/Listeners/UserReports/WritePsConsole.ps1

RunbookScanAgent and Command Alias Changes

---

src/AzSK/Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1
src/AzSK/Framework/Framework.ps1
src/AzSK/Framework/Helpers/ConfigurationHelper.ps1
src/AzSK/Framework/Listeners/GenericListener/GenericListener.ps1
src/AzSK/Framework/Listeners/GenericListener/GenericListenerBase.ps1
src/AzSK/Framework/Listeners/ListenerHelper.ps1
src/AzSK/Framework/Managers/ConfigurationManager.ps1

Listener extension model

---

src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

fixed port format issue on VM

---

src/AzSK/AzSK.pssproj
src/AzSK/Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Configurations/SVT/Services/Automation.json
src/AzSK/Framework/Configurations/SVT/Services/ContainerRegistry.json
src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json
src/AzSK/Framework/Core/SVT/Services/ContainerRegistry.ps1
src/AzSK/Framework/Helpers/SVTMapping.ps1

Added controls for Container Registry

---

src/AzSK/Framework/Configurations/SVT/AllResourceTypes.json

Added Container Registry, Container Instance resource type

---

src/AzSK/Framework/Listeners/RemoteReports/UsageTelemetry.ps1

AI telemetry issue fix

---

src/AzSK/Framework/Configurations/SVT/Services/ContainerRegistry.json

Added OwnerAccess Tag to exclude control while CA execution

---

src/AzSK/PolicySetup/PolicySetup.ps1
src/AzSK/SVT/FixControl.ps1
src/AzSK/SVT/SVT.ps1

changes as per testing

---

src/AzSK/Framework/Listeners/UserReports/WritePsConsole.ps1

chnages for alias greater than or equals to 5

---

src/AzSK/AzSKStaging.psd1

Added ContainerRegistry in psd1

---

src/AzSK/Framework/Abstracts/CommandBase.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetup.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/Framework/Models/AzSKSettings.ps1

Added check during CA install/update for local policy debug

---

src/AzSK/Framework/Configurations/SVT/Services/AppService.json
src/AzSK/Framework/Configurations/SVT/Services/KeyVault.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/RBAC.ps1

added 'OwnerAccess' tag + null check for deleted users

---

src/AzSK/AzSKStaging.psd1

Updated AzureRM.ContainerRegistry to latest version.

---

src/AzSK/Framework/Abstracts/CommandBase.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1

Bug fix and message updates

---

src/OSSConfiguration/ControlSettings.json

Updated Baseline list for OSS

---

src/AzSK/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK/Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/Framework/Helpers/UserSubscriptionDataHelper.ps1

Users tashuk patch 1809

---

src/AzSK/AzSK.psm1
src/AzSK/AzSKStaging.psd1
src/AzSK/Framework/Abstracts/SVTBase.ps1

AzureRM upgrade to version 6.8.1

---

src/AzSK/Framework/Helpers/ActiveDirectoryHelper.ps1

Changes in Update-AdAppCredential function

---

src/AzSK/Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Configurations/AzSk.json
src/AzSK/Framework/Core/SVT/Services/DataFactoryV2.ps1
src/AzSK/Framework/Models/AzSKConfig.ps1

Resource Metadata telemetry for ADF V2

---

src/AzSK/Framework/Configurations/SVT/Services/Automation.json

Modified the recommendation for the control "Azure_Automation_DP_Use_Encrypted_Variables"

Encrypted variable control automation recommendation changed

---

src/AzSK/Framework/Configurations/SVT/Services/LogicApps.json
src/AzSK/Framework/Configurations/SVT/Services/Storage.json
src/AzSK/Framework/Core/SVT/Services/LogicApps.ps1
src/AzSK/Framework/Core/SVT/Services/Storage.ps1

Bug fixes for Logic App and Storage service

---

src/AzSK/AzSK.pssproj
src/AzSK/Framework/Configurations/SVT/Services/ContainerRegistry.json
src/AzSK/Framework/Configurations/SVT/Services/VirtualNetwork.json
src/AzSK/Framework/Core/FixControl/Services/ContainerRegistryFix.ps1
src/AzSK/Framework/Core/SVT/Services/AppService.ps1
src/AzSK/Framework/Core/SVT/Services/ContainerRegistry.ps1
src/AzSK/Framework/Core/SVT/Services/ServiceFabric.ps1
src/AzSK/Framework/Core/SVT/Services/VirtualNetwork.ps1
src/AzSK/Framework/Helpers/SVTMapping.ps1

Fix VNet, Service Fabric controls

---

src/AzSK/Framework/Configurations/SVT/Services/SQLDatabase.json

changes for disbaling DB level controls for SQL

---

src/AzSK/Framework/Helpers/OMSHelper.ps1
src/AzSK/Framework/Listeners/OMS/OMSOutput.ps1

fixed - redundant OMS listener gets called inspite of invalid OMS settings

---

src/AzSK/Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/ARMPolicies.ps1
src/AzSK/Framework/Helpers/SecurityCenterHelper.ps1

Updated the ASC Policy apis within VM controls

---

src/AzSK/Framework/Core/AzureMonitoring/OMSMonitoring.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

</br>
1) Changed the state data for 'Azure_Subscription_AuthZ_Custom_RBAC_Roles', now it will only save role definitions with active assignment as state data.</br>
2) Formatting changes for messages in install-AzSKOMSSolution command.

Minor changes for install-AzSKOMSSolution messages formatting and state data change for CustomRBACRoles control

---

src/AzSK/Framework/Configurations/AzSKInfo/SecurityRecommendationReport.html
src/AzSK/Framework/Core/AzSKInfo/SecurityRecommendationsReport.ps1
src/AzSK/Framework/Helpers/Constants.ps1
src/AzSK/Framework/Listeners/SecurityRecommendationReport.ps1
src/AzSK/Framework/Models/RemoteReports/RecommendationReportModel.ps1

changed recommendation engine command

---

src/AzSK/Framework/Configurations/SVT/Services/KeyVault.json
src/AzSK/Framework/Core/SVT/Services/KeyVault.ps1

</br>
Fixed the control's behaviour in manual state and also rectified some error messages

Made required changes in the control 'Azure_KeyVault_DP_Keys_Secrets_Check_Expiry_Date'

---

src/AzSK/Framework/Configurations/SVT/Services/SQLDatabase.json

changes for removing deprecated control

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/AzSK/Framework/Core/ARMChecker/ARMCheckerStatus.ps1
src/AzSK/Framework/Helpers/Constants.ps1

updated the output message

---

src/AzSK/Framework/Core/SVT/Services/KeyVault.ps1

Chnages in message and behaviour of check expiry date control

---

src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1

ASC API issue fix

---

src/AzSK/Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Helpers/Constants.ps1
src/AzSK/Framework/Listeners/UserReports/WritePsConsole.ps1

Users/v nitja/ptach1809nitja

---

src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

</br>
Resolved the issue due to changes which caused VM metadata not getting captured properly in telemetry.

Changes for VM metadata issue 

---

src/AzSK/Framework/Configurations/SVT/Services/ContainerInstances.json
src/AzSK/Framework/Configurations/SVT/Services/ContainerRegistry.json
src/AzSK/Framework/Configurations/SVT/Services/RedisCache.json
src/AzSK/Framework/Configurations/SVT/Services/StreamAnalytics.json
src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json
src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/SVT/Services/RedisCache.ps1
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1
src/AzSK/Framework/Helpers/Helpers.ps1

</br>
1)Added Service specific tags to the controls
2)Removed SKU check for Redis Cache firewall control
3)Removed line of code where storage was getting deleted if an error occurred.

Service review fixes 

---

src/AzSK/Framework/Configurations/SVT/Services/CosmosDB.json
src/AzSK/Framework/Configurations/SVT/Services/DataLakeAnalytics.json
src/AzSK/Framework/Configurations/SVT/Services/KeyVault.json
src/AzSK/Framework/Configurations/SVT/Services/ServiceFabric.json
src/AzSK/Framework/Configurations/SVT/Services/TrafficManager.json
src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1

P2 non-baseline controls' bug fixes

---

src/AzSK/Framework/Configurations/SVT/Services/ServiceFabric.json
src/AzSK/Framework/Core/SVT/Services/ServiceFabric.ps1

Updated controls for service fabric

---

src/AzSK/Framework/Configurations/SVT/Services/AnalysisServices.json
src/AzSK/Framework/Configurations/SVT/Services/Automation.json
src/AzSK/Framework/Configurations/SVT/Services/DataLakeStore.json
src/AzSK/Framework/Configurations/SVT/Services/ServiceBus.json
src/AzSK/Framework/Core/SVT/Services/Automation.ps1

</br>
Automation webhook controls bug fixes along with inclusion of tags for service jsons and a recommendation update in a service json.

Control Validation (Bug Fix + Tags Inclusion)

---

src/AzSK/Framework/Configurations/SVT/Services/HDInsight.json
src/AzSK/Framework/Core/SVT/Services/HDInsight.ps1
src/AzSK/Framework/Helpers/SVTMapping.ps1

HDInsight Controls

---

src/AzSK/Framework/Core/SVT/SVTStatusReport.ps1
src/AzSK/SVT/SVT.ps1

Added ExcludeControlIds in GSS and GES

---

src/AzSK/Framework/Configurations/SVT/Services/Automation.json
src/AzSK/Framework/Configurations/SVT/Services/Batch.json
src/AzSK/Framework/Configurations/SVT/Services/DataLakeStore.json
src/AzSK/Framework/Configurations/SVT/Services/EventHub.json
src/AzSK/Framework/Configurations/SVT/Services/KeyVault.json
src/AzSK/Framework/Configurations/SVT/Services/LoadBalancer.json
src/AzSK/Framework/Configurations/SVT/Services/LogicApps.json
src/AzSK/Framework/Configurations/SVT/Services/RedisCache.json
src/AzSK/Framework/Configurations/SVT/Services/Search.json
src/AzSK/Framework/Configurations/SVT/Services/ServiceBus.json
src/AzSK/Framework/Configurations/SVT/Services/StreamAnalytics.json

</br>
To offer an alternate solution for the known bug regarding Set-AzureRMDiagnosticSetting command

Updated recommendations that have Set-AzureRmDiagnosticSetting command

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

Removed 'Security reader' role check/assignment in CA 

---

src/AzSK/Framework/Configurations/AzSKInfo/CategoryHash.json
src/AzSK/Framework/Configurations/AzSKInfo/CategoryMapping.json
src/AzSK/Framework/Configurations/AzSKInfo/SecurityRecommendationReport.html
src/AzSK/Framework/Core/AzSKInfo/SecurityRecommendationsReport.ps1
src/AzSK/Framework/Listeners/SecurityRecommendationReport.ps1
src/AzSK/Framework/Models/RemoteReports/RecommendationReportModel.ps1

minor changes in recommendation engine

---

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetup.ps1
src/AzSK/Framework/Core/PolicySetup/EasyInstaller.ps1

changes for config compare

---

src/AzSK/ARMChecker/ARMChecker.ps1

Removed Preview from ARM Checker

---

src/AzSK.ARMChecker.Lib/ArmTemplateEvaluator.cs
src/AzSK/Framework/Configurations/SVT/Services/Batch.json
src/AzSK/Framework/Configurations/SVT/Services/DataLakeStore.json
src/AzSK/Framework/Configurations/SVT/Services/EventHub.json
src/AzSK/Framework/Configurations/SVT/Services/KeyVault.json
src/AzSK/Framework/Configurations/SVT/Services/LogicApps.json
src/AzSK/Framework/Configurations/SVT/Services/SQLDatabase.json
src/AzSK/Framework/Configurations/SVT/Services/Search.json
src/AzSK/Framework/Configurations/SVT/Services/ServiceBus.json
src/AzSK/Framework/Configurations/SVT/Services/ServiceFabric.json
src/AzSK/Framework/Configurations/SVT/Services/Storage.json
src/AzSK/Framework/Configurations/SVT/Services/StreamAnalytics.json

added policy guiids

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Configurations/SVT/Services/Batch.json
src/AzSK/Framework/Configurations/SVT/Services/DataLakeStore.json
src/AzSK/Framework/Configurations/SVT/Services/EventHub.json
src/AzSK/Framework/Configurations/SVT/Services/KeyVault.json
src/AzSK/Framework/Configurations/SVT/Services/LogicApps.json
src/AzSK/Framework/Configurations/SVT/Services/SQLDatabase.json
src/AzSK/Framework/Configurations/SVT/Services/Search.json
src/AzSK/Framework/Configurations/SVT/Services/ServiceBus.json
src/AzSK/Framework/Configurations/SVT/Services/ServiceFabric.json
src/AzSK/Framework/Configurations/SVT/Services/Storage.json
src/AzSK/Framework/Configurations/SVT/Services/StreamAnalytics.json

added policy defids

---

src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1

Key Secret permission warning message not showing in bulk attestation mode

---

src/AzSK/Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/ARMPolicies.ps1
src/AzSK/Framework/Models/SVT/SVTConfig.ps1

minor change to svtconfig

---

src/AzSK/Framework/Configurations/SVT/Services/Databricks.json
src/AzSK/Framework/Core/SVT/Services/Databricks.ps1

</br>
1- Added "Databricks" tag in JSON.
2- Refactored code to remove "Token Read" logic from constructor.

Removed Token read code from constructor

---

src/AzSK/Framework/Helpers/ConfigurationHelper.ps1

Fixed warning messages

---

src/AzSK/Framework/Core/SVT/SVTResourceResolver.ps1

Exclude Rg/resources minor changes in spacing for warning messages.

---

src/AzSK/Framework/Configurations/SVT/Services/Databricks.json
src/AzSK/Framework/Core/SVT/Services/Databricks.ps1

Updated message for DB control in DataBricks service

---

src/AzSK/AzSKStaging.psd1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/HDInsight.json
src/AzSK/Framework/Core/SVT/Services/HDInsight.ps1

HDInsight Control Automation

---

src/AzSK/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK/Framework/Listeners/RemoteReports/RemoteReportsListener.ps1

1) Changes for capturing SubscriptionId for resourceflatinventory 
2) Minor message fix for parameter check of exclude resource group name.

Changes to capture SubscriptionId correctly in resourceflatinventory

---

src/AzSK/Framework/Listeners/RemoteReports/AIOrgTelemetry.ps1
src/AzSK/Framework/Listeners/RemoteReports/RemoteReportsListener.ps1

Enabling prod and non-prod tag capture in DB

---

src/AzSK/AzSK.psm1
src/AzSK/Framework/Abstracts/AzSKRoot.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Helpers/ConfigOverride.ps1
src/AzSK/Framework/Helpers/ConfigurationHelper.ps1
src/AzSK/Framework/Helpers/Constants.ps1
src/AzSK/Framework/Helpers/Helpers.ps1
src/AzSK/Framework/Helpers/WebRequestHelper.ps1
src/AzSK/Framework/Models/AzSKSettings.ps1

azure cloud changes

---

src/AzSK/Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1
src/AzSK/Framework/Managers/PartialScanManager.ps1
src/AzSK/SVT/SVT.ps1
src/OSSConfiguration/RunbookScanAgent.ps1

</br>
GCA needs to be handled. SPN permissions for attested data also needs to be handled.

Skip AzSKRG in central scan mode store ca-scan-checkpoints on master sub

---

src/AzSK/Framework/Listeners/RemoteReports/RemoteReportsListener.ps1

Removed hidden encoded character

---

src/AzSK/Framework/Core/SVT/Services/KubernetesService.ps1

Used WebRequestHelper helper method to get management Uri

---

src/AzSK/Framework/Configurations/SVT/Services/Databricks.json
src/AzSK/Framework/Core/SVT/Services/Databricks.ps1

Automated databricks manual controls

---

src/AzSK/Framework/Listeners/RemoteReports/AIOrgTelemetry.ps1
src/AzSK/Framework/Listeners/RemoteReports/RemoteReportsListener.ps1

 updated to fix subscription ID fetch for resourceFlat

---

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/OSSConfiguration/RunbookScanAgent.ps1

handled $null value for central storage

---

src/AzSK/Framework/Configurations/SVT/Services/KubernetesService.json
src/AzSK/Framework/Core/SVT/Services/KubernetesService.ps1
src/AzSK/Framework/Helpers/WebRequestHelper.ps1

Update AKS controls as per feedback and handle duplicate keys ConvertFrom-Json issue

---

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/OSSConfiguration/RunbookScanAgent.ps1

Config Sync from Prod Env

---

src/AzSK/Framework/Configurations/SVT/Services/APIManagement.json

Updated recommendation

---

src/AzSK/Framework/Configurations/ContinuousAssurance/Continuous_Assurance_Runbook.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/Continuous_Assurance_ScanOnTrigger_Runbook.ps1

Fixed EnvironmentName issue

---

src/AzSK/Framework/Managers/PartialScanManager.ps1

CA Central Scan Checkpoint Issue fix

---

src/AzSK/Framework/Helpers/ConfigurationHelper.ps1

armchecker task issue

---

src/AzSK/Framework/Helpers/Helpers.ps1

Skipped tag exception warning for reader roles

---

src/AzSK/Framework/Configurations/SVT/Services/Automation.json
src/AzSK/Framework/Configurations/SVT/Services/Batch.json
src/AzSK/Framework/Configurations/SVT/Services/DataLakeAnalytics.json
src/AzSK/Framework/Configurations/SVT/Services/DataLakeStore.json
src/AzSK/Framework/Configurations/SVT/Services/EventHub.json
src/AzSK/Framework/Configurations/SVT/Services/KeyVault.json
src/AzSK/Framework/Configurations/SVT/Services/LoadBalancer.json
src/AzSK/Framework/Configurations/SVT/Services/LogicApps.json
src/AzSK/Framework/Configurations/SVT/Services/RedisCache.json
src/AzSK/Framework/Configurations/SVT/Services/Search.json
src/AzSK/Framework/Configurations/SVT/Services/ServiceBus.json
src/AzSK/Framework/Configurations/SVT/Services/StreamAnalytics.json

Recommendation update for diagnostic settings

---

src/AzSK/Framework/Core/ARMChecker/ARMCheckerStatus.ps1
src/AzSK/Framework/Core/PolicySetup/EasyInstaller.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/Framework/Listeners/CA/WriteCAStatus.ps1
src/AzSK/PolicySetup/PolicySetup.ps1

ARMChecker bug fix, OrgPolicy for Azure Gov and Azure policy changes

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

</br>
Null condition fix for PIM control

Bug fix for PIM control

---

src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1
src/AzSK/Framework/Helpers/ComplianceReportHelper.ps1
src/AzSK/Framework/Helpers/OMSHelper.ps1
src/AzSK/Framework/Listeners/UserReports/WriteSummaryFile.ps1
src/AzSK/Framework/Models/RemoteReports/ComplianceStateModel.ps1
src/AzSK/Framework/Models/RemoteReports/CsvOutputModel.ps1
src/AzSK/Framework/Models/SVT/SVTEvent.ps1

</br>
This PR includes the following changes</br>
1) Storing 'IsControlInGrace' flag in storage table.</br>
2) Computing Compliance with and without grace</br>
3) Sending 'IsControlInGrace' flag in OMS event</br>
4) Added 'IsControlInGrace' column is scan report and compliance report.</br>

Changes for timeline based compliance

---

src/AzSK/AzSKInfo/AzSKInfo.ps1
src/AzSK/Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1
src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1
src/AzSK/Framework/Listeners/UserReports/WritePsConsole.ps1
src/AzSK/Framework/Models/FixControl/FixControlModel.ps1
src/AzSK/Framework/Models/RemoteReports/LSRScanResultModel.ps1
src/AzSK/Framework/Models/RemoteReports/ScanResultModels.ps1
src/AzSK/Framework/Models/SVT/SVTConfig.ps1

Baseline VNext changes for control severity

---

src/AzSK/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK/Framework/Core/SVT/Services/AppService.ps1

</br>
Changes for accepting multiple values in -TagValue parameter  and added metadata in AppService

Changes for accepting multiple values in -TagValue parameter in GRS

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/KubernetesService.json
src/AzSK/Framework/Core/SVT/Services/EventHub.ps1
src/AzSK/Framework/Core/SVT/Services/KubernetesService.ps1
src/OSSConfiguration/ARMControls.json

Added new controls in Kubernetes Service

---

src/AzSK/Framework/Core/ARMChecker/ARMCheckerStatus.ps1
src/AzSK/Framework/Listeners/UserReports/WritePsConsole.ps1

changes for Org-Policy severity

---

src/AzSK/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK/SVT/SVT.ps1

</br>
Null value handling for the condition when no resources with matching TagValues are found.

Bug fix for -TagValue parameter

---

src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1

</br>
Minor header changes for the output of command

UI changes for Compliance State summary

---

src/AzSK/Framework/Configurations/SVT/Services/APIManagement.json
src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

- Updated APIManagement.json
- Updated APIManagement.ps1

APIM new controls.

---

src/AzSK/AzSK.psm1
src/AzSK/Framework/Listeners/OMS/OMSOutput.ps1

Bug fix for Login in Listener Registration

---

src/AzSK/Framework/Configurations/SVT/Services/KubernetesService.json

Fix recommendation of AKS diagnostics control

---

src/AzSK/Framework/Core/ARMChecker/ARMCheckerStatus.ps1
src/AzSK/PolicySetup/PolicySetup.ps1

policy setup bug fix

---

src/AzSK/Framework/Abstracts/SVTBase.ps1

changes for attestation date issue

---

src/AzSK/Framework/Configurations/SVT/Services/APIManagement.json
src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

Fixed error in APIManagement.ps1
Updated Recommendation

Fixed error in APIManagement.ps1

---

src/AzSK/Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Core/SVT/Services/LoadBalancer.ps1

changes for error in control "Azure_LoadBalancer_NetSec_Justify_PublicIPs"

---

src/AzSK/ARMCheckerLib/controls.gen.json
src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/AzSK/Framework/Configurations/SVT/Services/CosmosDB.json
src/OSSConfiguration/ARMControls.json

Edited recommendation message

---

src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1

Skip older child control results in ComplianceInfo calculation

---

src/AzSK/Framework/Core/SVT/Services/APIConnection.ps1

</br>
Added check member to solve error 'The property 'uri' cannot be found on this object. Verify that the property exists' that occurs  in case of blank logic app

Added check member 

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/Services/Automation.ps1

Whitelisted variables in CA Automation Account

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json

Add type in local ARMControl for AKS control

---

src/AzSK/Framework/Helpers/OMSHelper.ps1

</br>
This would result in a field added in the OMS events showing the id that ran the scan.

Added ScannedBy in OMS properties

---

src/AzSK/Framework/Configurations/SVT/Services/APIManagement.json
src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

- Updated APIM logic to filter controls based on tags.
</br>

- Added 'APIMAPIs' and 'APIMProducts' tags to APIM controls.

---

src/AzSK/Framework/Configurations/SVT/Services/AppService.json

</br>
Added reference link in the recommendation for Azure_AppService_Deploy_Dont_Use_Publish_Profiles.

Updated reco for Azure_AppService_Deploy_Dont_Use_Publish_Profiles

---

src/AzSK/AzSKInfo/AzSKInfo.ps1
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1
src/AzSK/Framework/Helpers/ComplianceReportHelper.ps1
src/AzSK/Framework/Helpers/RemoteApiHelper.ps1

*  Includes changes for fetching compliance info from back end for a subscription 
* Added alias to GAI parameters
* Bug fix for GAI -infoType AttestationInfo

Bootstrapping Compliance Info 

---

src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1

* Changes to scan single API Connection once even it is linked to multiple Logic Apps.

Changes to scan of ChildResources

---

src/AzSK/AzSKInfo/AzSKInfo.ps1
src/AzSK/Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/AzSKInfo/ControlsInfo.ps1
src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1
src/AzSK/Framework/Listeners/UserReports/WriteSummaryFile.ps1
src/AzSK/Framework/Managers/PartialScanManager.ps1
src/AzSK/SVT/SVT.ps1

UsePreviewBaseline Funcitonality and Mandatory Tag Control

---

src/AzSK/Framework/Core/PolicySetup/AzSKStaging-EasyInstaller.ps1
src/AzSK/Framework/Core/PolicySetup/EasyInstaller.ps1

Removes "AzSDK" check from contoso org

---

src/AzSK/Framework/Core/AzSKInfo/ControlsInfo.ps1
src/OSSConfiguration/ControlSettings.json

Fixed Subscription Control listing issue in GAI

---

src/AzSK/AzSKInfo/AzSKInfo.ps1
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1
src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1

* Modified the logic for childSvt scan
* Added Alias for Sync parameter in GAI

Bug fixes for API Connection getting scanned multiple times

---

src/AzSK/Framework/Core/SVT/AzSKCfg/AzSKCfg.ps1

</br>
If user does not have any permissions on AzSKRG, config controls should result manual rather than failed.

Fixing bug with Cfg control failing due to no permissions

---

src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json

Corrected recommendation for Azure_Subscription_Config_Add_Required_Tags

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Core/SVT/Services/Storage.ps1

</br>
The retention log period has to be AT LEAST the one mentioned in ControlSettings, and not necessarily be equal to that.

Fix for Log Retention period (days)

---

src/AzSK/Framework/Core/AzSKInfo/ControlsInfo.ps1

Added control severity logic

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Helpers/ComplianceReportHelper.ps1
src/AzSK.Framework/Helpers/OMSHelper.ps1
src/AzSK.Framework/Helpers/RemoteReportHelper.ps1
src/AzSK.Framework/Listeners/RemoteReports/AIOrgTelemetry.ps1
src/AzSK.Framework/Models/RemoteReports/ScanResultModels.ps1
src/AzSK.Framework/Models/SVT/SVTConfig.ps1
src/AzSK/Framework/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/AzSK.Framework/Helpers/ComplianceReportHelper.ps1
src/AzSK/Framework/AzSK.Framework/Helpers/OMSHelper.ps1
src/AzSK/Framework/AzSK.Framework/Helpers/RemoteReportHelper.ps1
src/AzSK/Framework/AzSK.Framework/Listeners/RemoteReports/AIOrgTelemetry.ps1
src/AzSK/Framework/AzSK.Framework/Models/RemoteReports/ScanResultModels.ps1
src/AzSK/Framework/AzSK.Framework/Models/SVT/SVTConfig.ps1
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

Adding IsPreviewBaselineFlag in control results 

---

src/AzSK/Framework/Core/AzureMonitoring/OMSMonitoring.ps1

Updated OMS View override warning

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/ARMCheckerLib/controls.gen.json
src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/AppService.json
src/OSSConfiguration/ARMControls.json

</br>
Updated the .Net framework version from 4.0 to 4.7

.Net framework version update

---

src/AzSK.Framework/Listeners/RemoteReports/AIOrgTelemetry.ps1

Resource group tag bug fix

---

src/AzSK.Framework/Helpers/OMSHelper.ps1
src/AzSK.Framework/Listeners/OMS/OMSOutput.ps1
src/AzSK/Framework/Helpers/OMSHelper.ps1
src/AzSK/Framework/Listeners/OMS/OMSOutput.ps1
src/OSSConfiguration/RunbookScanAgentBackUp.ps1

The message now includes the workspace name as well.
</br>
Updated the message as per discussion and to include the WS name as well.

Fixed the message

---

src/AzSK/Framework/Core/PolicySetup/AzSKStaging-EasyInstaller.ps1

updated dtlgallery url to poshtestgallery url for Contoso

---

src/AzSK.Framework/Helpers/Helpers.ps1
src/AzSK/AzSK.psm1
src/AzSK/Framework/Helpers/Helpers.ps1

</br>
Changing the approach for acquiring token.

Solving token issue

---

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetup.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetupAzureRm.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/OSSConfiguration/RunbookCoreSetup.ps1
src/OSSConfiguration/RunbookCoreSetupAzureRm.ps1
src/OSSConfiguration/RunbookScanAgent.ps1

Url changes

---

src/AzSK.Framework/Helpers/AzHelper.ps1
src/AzSK.Framework/Managers/ControlStateExtension.ps1
src/AzSK/Framework/Helpers/AzHelper.ps1
src/AzSK/Framework/Managers/ControlStateExtension.ps1

- Updated AzHelper.ps1
- Updated ControlStateExtension.ps1

Fixed fresh attestation and re-attestation issue.

---

src/AzSK/Framework/Helpers/Helpers.ps1

Adding null check to tags while setting resource tags

---

src/AzSK.Framework/Helpers/Helpers.ps1
src/AzSK/Framework/Helpers/Helpers.ps1

Adding null check while setting resourcetags

---

src/AzSK.Framework/Managers/ControlStateExtension.ps1
src/AzSK/Framework/Managers/ControlStateExtension.ps1

- Updated ControlStateExtension.ps1

Attestation Fix

---

src/AzSK/Framework/Configurations/SVT/Services/VirtualNetwork.json

reco change

---

src/AzSK/Framework/Configurations/ContinuousAssurance/Continuous_Assurance_Runbook.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetup.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetupAzureRm.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/OSSConfiguration/RunbookCoreSetup.ps1
src/OSSConfiguration/RunbookCoreSetupAzureRm.ps1
src/OSSConfiguration/RunbookScanAgent.ps1
src/OSSConfiguration/RunbookScanAgentAzureRm.ps1

Added telemetry events for CA Az upgrade

---

src/OSSConfiguration/ControlSettings.json

</br>
Updated the UPBC list as per the latest discussion (03/06/2019).

Updated the UPBC list as per 03/06/2019

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

</br>
- Simplified the nested Where-Object clause.
- Comparison with $null replaced by [string]::IsNullOrWhiteSpace(), to make sure empty objects are also considered.

Fixed the RGs list logic

---

src/AzSK.Framework/Listeners/OMS/OMSOutput.ps1
src/AzSK/Framework/Listeners/OMS/OMSOutput.ps1

</br>
GxS:  Log Analytics workspace Info - Removed WS name

GxS: Log Analytics Info: Removed WSName

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

</br>
In case when the CA runbook requires update, changed the recommendation to run UCA rather than USS.

Updated the reco to UCA rather than USS

---

src/AzSK/Framework/Core/SVT/Services/Storage.ps1

</br>
In case there is no container in the Storage account, the API call still returns a blank object. Added a check to verify if its value is null/white space.

Fix for Property not found error

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/Services/Databricks.ps1
src/AzSK/Framework/Core/SVT/Services/KubernetesService.ps1
src/AzSK/Framework/Core/SVT/Services/ServiceFabric.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1

Set and Get ASC Policies Bug fix  

---

src/AzSK/AlertMonitoring/OMS.ps1

Put a check on when to display the warning

---

src/AzSK/Framework/Models/AzSKConfig.ps1

</br>
The MintenanceMessage in HostInfo was coming as blank/{0}. Fixed that to show the latest AzSK* version.

Added version to HostInfo Maintenance message

---

src/AzSK/Framework/Configurations/AlertMonitoring/AZSK.AM.OMS.GenericView.V3.omsview
src/AzSK/Framework/Core/AzureMonitoring/OMSMonitoring.ps1

Added updated views

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/APIManagement.json
src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

a. Updated APIManagement.json
- Updated recommendation
- Updated tags
b. Updated APIManagement.ps1
- updated CheckAADIdentityProviderEnabled logic
- updated controlResult message
- Added null check

API Management UPBC control update

---

src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1

Fix for bug 4393952

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json

Updated NetFrameworkVersion 4.7 to 4.0

---

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetupAzureRm.ps1
src/OSSConfiguration/RunbookCoreSetupAzureRm.ps1

Minor changes in the logic

---

src/AzSK/Framework/Configurations/SVT/Services/Storage.json

</br>
This is to enable the scan of this control in CA using the API (feature flighting approach).

Removed the Owner access tag

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

ASC tier Control

---

src/AzSK/Framework/Configurations/FeatureFlighting.json

</br>
Enabled feature flighting for scanning Anonymous Access on Storage.

Enabled Anonymous access check

---

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetupAzureRm.ps1
src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/OSSConfiguration/RunbookCoreSetupAzureRm.ps1

Minor bug fixes

---

src/AzSK/Framework/Configurations/ContinuousAssurance/Continuous_Assurance_Runbook.ps1

Removed extra brace

---

src/AzSK.Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Perf fix and RG fix for scan agent

---

src/OSSConfiguration/RunbookScanAgent.ps1

removed access token for oss

---

src/OSSConfiguration/RunbookCoreSetup.ps1
src/OSSConfiguration/RunbookCoreSetupAzureRm.ps1

Updated CS

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Added code for whitelisting few permanent PIM accounts

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

</br>
Modified the message where the runbook version was too old and in logs its status was OK.

Bug fix for GCA warning message

---

src/AzSK/Framework/Core/SVT/Services/AppService.ps1

-Fixed control error for stopped app service

Updated AppService.ps1

---

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetupAzureRm.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/AzSK/Framework/Configurations/FeatureFlighting.json
src/OSSConfiguration/RunbookCoreSetupAzureRm.ps1
src/OSSConfiguration/RunbookScanAgent.ps1
src/OSSConfiguration/RunbookScanAgentAzureRm.ps1

Coresetup bug fix and switching back to AzStorage command

---

src/AzSK/Framework/Core/ARMChecker/ARMCheckerStatus.ps1

ArmChecker bug fix

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1

</br>
Added the switch to Connect-AzAccount in warnings/messages in order to fix the PS ISE freeze issue.

Updated messages for PS Freeze issue

---

src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json

Updated the reco to include a note that the user needs to wait for some time for the settings to reflect in ASC.
</br>

Reco update

---

src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json
src/AzSK/Framework/Core/ARMChecker/ARMCheckerStatus.ps1
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

Added control to check Guest Configuration extension on VM

---

src/AzSK/Framework/Configurations/ContinuousAssurance/Continuous_Assurance_ScanOnTrigger_Runbook.ps1

- Added check for $Global:isAzAvailable in Continuous_Assurance_ScanOnTrigger_Runbook.ps1 file

Fixed CA -scanondeployment bug.

---

src/AzSK.Framework/Helpers/AzHelper.ps1

Partial scan manager bug fix

---

src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

Changed control behavior from Error to Manual when the scope is locked

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1

PIM Script issue fixes

---

src/AzSK/Framework/Configurations/AlertMonitoring/AZSK.AM.OMS.GenericView.V4.omsview
src/AzSK/Framework/Core/AzureMonitoring/OMSMonitoring.ps1

Added new filters

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

Fixed GCA scan error when CA components are missing.

---

src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1

Fix for bracket removal

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Bug fix for value type case issue in Mandatory Tag control

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

Moved Extension Name and Version to Control Settings file

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgentAzureRm.ps1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/OSSConfiguration/ARMControls.json
src/OSSConfiguration/RunbookScanAgent.ps1

Config Comparison OSS to module

---

src/AzSK/Framework/Configurations/SubscriptionSecurity/Subscription.ARMPolicies.json

Added the missing ARM policies in the deprecated list.
</br>

Deprecated List update

---

src/AzSK/Framework/Configurations/SVT/Services/AppService.json

</br>
Updated recommendation to clarify that UnauthenticatedClientAction is not allowed anymore, as previously passing controls are failing now for that reason.

Updating AppService AAD control recommendation

---

src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

Fixed CA stuck issue

---

src/AzSK/Framework/Configurations/SubscriptionSecurity/SecurityCenter.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenterStatus.ps1
src/AzSK/SubscriptionSecurity/SecurityCenter.ps1

Revert "Enforcing mandatory and optional ASC default initiative policies."

---

src/AzSK.Framework/Abstracts/CommandBase.ps1
src/AzSK.Framework/Helpers/CommandHelper.ps1
src/AzSK.Framework/Models/CommandDetails.ps1

Corrected variable name "IsOrgPolicyTagRequired"

Corrected variable name "IsOrgPolicyTagRequired"

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Changed CheckCriticalAlertsPresence function logic

---

src/AzSK/Framework/Configurations/SubscriptionSecurity/Subscription.InsARMAlerts.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Deploy and Check only mandatory alerts

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Helpers/CommandHelper.ps1

1905 bug fixes

---

src/AzSK.Framework/Helpers/AIOrgTelemetryHelper.ps1
src/AzSK.Framework/Listeners/UserReports/WritePsConsole.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

Updated GCA behaviour for older runbook version and fixed AIOrgTelmetry issue for event property add method

---

src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1

commented listerner cleanup code causing issue with listerner output

---

src/AzSK/Framework/Configurations/SubscriptionSecurity/SecurityCenter.json

added more policies to SecurityCenter.json

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/Services/AppService.ps1

Bug fix: Azure_AppService_AuthN_Use_AAD_for_Client_AuthN

---

src/AzSK/Framework/Core/SVT/Services/KeyVault.ps1

key vault new control bug fix

---

src/AzSK/Framework/Core/SVT/Services/KeyVault.ps1

</br>
Added exception handling for key vault error exception

KV new control bugfix

---

src/AzSK.Framework/Helpers/CommandHelper.ps1

Disabled PIM commands dependency on org-Policy

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

Made Guest Config Assignment check configurable

---

src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SubscriptionSecurity.ps1

fixed USS and SSS.

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/OSSConfiguration/ARMControls.json

ARMChecker Vnet control bugfix

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/OSSConfiguration/ARMControls.json

udated ARM controls file for OSS

---

src/AzSK/Framework/Configurations/SubscriptionSecurity/Subscription.InsARMAlerts.json

Modifed alerts operations list

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json

- Updated ARM checker control "Azure_SQLDatabase_Audit_Enable_Threat_Detection_Server". Changed matchtype from 'StringSingleToken' to 'Boolean'.

Changed matchtype from 'StringSingleToken' to 'Boolean'

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/PIM/PIM.ps1

Updated PIM command to take DoNotOpenFolder by default.

PIM bugfix

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

1. Added additional check to filter mandatory operations
2. Added null check in case no alerts have been configured on the azure portal

Updated CheckCriticalAlertsPresence function (to check log alerts)

---

src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

Added null check in restrict caller IP control

Added null check in restrict caller IP control

---

src/AzSK.Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

Added new controls in VM and skipped controls for databricks locked VMs

---

src/AzSK.Framework/Helpers/ComplianceReportHelper.ps1
src/AzSK.Framework/Models/RemoteReports/ComplianceStateModel.ps1
src/AzSK.Framework/Models/SubscriptionCore/AzureSecurityCenter.ps1
src/AzSK/AzSKInfo/AzSKInfo.ps1
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Changes for ASC control and CompliancInfo cmd

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

</br>
added null check for empty operations object

bugfix: null check for empty operations object

---

src/AzSK/Framework/Configurations/SVT/Services/KeyVault.json
src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1

Removed duplicate resources from ubc and upbc scan

---

src/AzSK/Framework/Configurations/SVT/Services/APIManagement.json
src/AzSK/Framework/Configurations/SVT/Services/Batch.json
src/AzSK/Framework/Configurations/SVT/Services/StreamAnalytics.json

Updated steps to setup metric alert

Updated recommendations

---

src/AzSK.Framework/Listeners/LogAnalytics/LogAnalyticsOutput.ps1

</br>
Fixed the bug where logs were not being sent to Log Analytics workspace (AzSK_CL)

Bug fixed: Log Analytics AzSK_CL not receving logs

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/AzSK/Framework/Core/AzSKInfo/ControlsInfo.ps1
src/OSSConfiguration/ARMControls.json

Added IsPreviewBaselineControl in GAI Control Info

---

src/AzSK/Framework/Core/SVT/Services/SQLDatabase.ps1

Fixed SQL bugs

---

src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json

Updated Json for VM controls

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/Framework/Core/SVT/Services/AppService.ps1

CheckAppServiceInstanceCount function: Added null check
PIM ListPIMAssignments: Printing additional column 'AssignmentState' = Eligible/Active

Bugfix: Appservice BCDR control and PIM ListPIMAssignments duplicate value

---

src/AzSK/Framework/Configurations/SubscriptionSecurity/SecurityCenter.json
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1

Cmd added to update security version tag on AzSKRG and removed hardcoding

---

src/AzSK/Framework/Core/SVT/Services/ERvNet.ps1

ERNetwork mandatory ARM Policy control

---

src/AzSK.Framework/Helpers/ComplianceReportHelper.ps1
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1

IsPreviewBaseline Fix  For Compliance Info

---

src/AzSK.Framework/Abstracts/SVTBase.ps1

-> Updated API to fetch alerts at resource level
-> Add null check if new alerts not found
</br>

Metric alert bug fix

---

src/AzSK/Framework/Configurations/SubscriptionSecurity/SecurityCenter.json

correcting diagnostics log in KV policy effect

---

src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1

reverting changes to 1905 and added SecCenter version update code.

---

src/AzSK/Framework/Configurations/SVT/Services/Storage.json

Added tags for file type storage

---

src/AzSK.Framework/Helpers/CommandHelper.ps1

GAI cmdlet: Disabled the mandatory org-policy check

 GAI cmdlet: Disabled the mandatory org-policy check

---

src/AzSK/AzSK.psm1
src/AzSK/Framework/Configurations/AzSkSettings.json
src/AzSK/Framework/Core/PolicySetup/AzSKStaging-EasyInstaller.ps1
src/AzSK/Framework/Core/PolicySetup/EasyInstaller.ps1
src/OSSConfiguration/RunbookCoreSetup.ps1

Added recovery code for stuck module

---

src/AzSK.ARMChecker.Lib/ControlDataMatchType.cs
src/AzSK.ARMChecker.Lib/ControlEvaluator.cs
src/AzSK.ARMChecker.Lib/ControlMatchType.cs
src/AzSK/Framework/Core/SubscriptionSecurity/Alerts.ps1

Bug fixes 1907

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1

Previously, we were fetching the complete list of resource groups that user had access to. In this PR, I have updated the API to filter resources based on name and fetch only relevant resource details.

bugfix- updated API to fetch resources based on resource name

---

src/AzSK.Framework/Listeners/LogAnalytics/LogAnalyticsOutput.ps1

Added handling in case LA workspace is not configured

---

src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Build.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Release.ps1
src/AzSK.Framework/Abstracts/CommandBase.ps1
src/AzSK.Framework/Abstracts/FileOutputBase.ps1
src/AzSK.Framework/Helpers/AzHelper.ps1
src/AzSK.Framework/Helpers/ConfigOverride.ps1
src/AzSK.Framework/Helpers/ConfigurationHelper.ps1
src/AzSK.Framework/Helpers/Constants.ps1
src/AzSK.Framework/Helpers/Helpers.ps1
src/AzSK.Framework/Helpers/ResourceHelper.ps1
src/AzSK.Framework/Listeners/FixControl/WriteFixControlFiles.ps1
src/AzSK.Framework/Listeners/UserReports/WriteFolderPath.ps1
src/AzSK.Framework/Managers/ConfigurationManager.ps1
src/AzSK.Framework/Managers/ControlStateExtension.ps1
src/AzSK.Framework/Managers/PartialScanManager.ps1
src/AzSK.Framework/Models/AzSKSettings.ps1
src/AzSK/AzSKStaging.psd1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgentAzureRm.ps1
src/AzSK/Framework/Core/ARMChecker/ARMCheckerStatus.ps1
src/AzSK/Framework/Core/AzureMonitoring/LogAnalyticsMonitoring.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/FixControl/ControlSecurityFixes.ps1
src/AzSK/Framework/Core/FixControl/FixControlConfigResolver.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1
src/OSSConfiguration/RunbookScanAgent.ps1
src/OSSConfiguration/RunbookScanAgentAzureRm.ps1

PS Core changes

---

src/AzSK.Framework/Helpers/CommandHelper.ps1
src/AzSK.Framework/Helpers/WebRequestHelper.ps1
src/AzSK/Framework/Core/AzSKInfo/EnvironmentInfo.ps1
src/AzSK/Framework/Core/PIM/PIMScript.ps1

Bug fix for PIM

---

src/AzSK.Framework/Models/SubscriptionSecurity/SubscriptionRBAC.ps1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Added a new control to check permanent access at rg level

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Helpers/Helpers.ps1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/SVTIaasBase.ps1
src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1

Fixed filterTags/excludeTags issue and added "User Access Admin" as critical PIM role

---

src/AzSK.Framework/Helpers/RemoteReportHelper.ps1

Adding ToLower() in Mask

---

src/AzSK.Framework/Abstracts/AzSKRoot.ps1
src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Helpers/Helpers.ps1
src/AzSK.Framework/Helpers/WebRequestHelper.ps1
src/AzSK/Framework/Configurations/AzSkSettings.json
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/ARMChecker/ARMCheckerStatus.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/OSSConfiguration/RunbookScanAgent.ps1

Fixed PIM issue for web response, CA SPN permission, ARM Policies, CA scan to RG names, other fixes

---

src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1

ASC multiple initiative issue resolved

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/AppService.json
src/AzSK/Framework/Core/SVT/Services/AppService.ps1

Added new controls for App Service

---

src/AzSK.Framework/Abstracts/AzSKRoot.ps1

</br>
Changed as per discussion.

Message updated in case PIM is not activated

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Abstracts/SVTCommandBase.ps1
src/AzSK.Framework/Helpers/ComplianceReportHelper.ps1
src/AzSK.Framework/Helpers/ConfigurationHelper.ps1
src/AzSK.Framework/Listeners/CA/WriteCAStatus.ps1
src/AzSK.Framework/Managers/ControlStateExtension.ps1
src/AzSK.Framework/Models/SVT/SVTEvent.ps1
src/AzSK.Framework/Models/SVT/SVTResource.ps1
src/AzSK/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1
src/AzSK/Framework/Core/SVT/Services/ContainerRegistry.ps1
src/AzSK/Framework/Core/SVT/Services/Databricks.ps1
src/AzSK/Framework/Core/SVT/Services/SQLDatabase.ps1
src/AzSK/Framework/Core/SVT/ServicesSecurityStatus.ps1
src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1

Performance changes for AzSK module

---

src/AzSK.Framework/Helpers/Constants.ps1
src/AzSK/AzSK.psm1
src/AzSK/AzSKStaging.psd1
src/AzSK/CredRotation/CredRotation.ps1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/CredRotation/CredRotationScript.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Framework.ps1

Key rotation solution

---

src/AzSK.Framework/Helpers/CommandHelper.ps1
src/AzSK/AzSK.psm1
src/AzSK/CredHygiene/CredHygiene.ps1
src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/CredHygiene/CredHygieneScript.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Framework.ps1

</br>
1. Added switch 'ResetLastUpdate' in Update-AzSKTrackedCredential to just update the last updated timestamp.
2. Updated messages.
3. Updated detailed log info for the GSS control 'Azure_Subscription_Check_Credential_Rotation'

Key rotation

---

src/AzSK.Framework/Abstracts/SVTCommandBase.ps1
src/AzSK.Framework/Helpers/SecurityCenterHelper.ps1
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

Fixed performance issue in VM ASC controls
- Removed  [SecurityCenterHelper]::ASCSecurityStatus
- Updated ASC API to fetch resource specific details recommendations only.

Fixed performance issue in VM ASC controls

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1

disable feature flighting for asc telemetry

---

src/OSSConfiguration/ControlSettings.json

UPBC -> UBC

---

src/AzSK.Framework/Helpers/WebRequestHelper.ps1
src/AzSK/Framework/Core/PIM/PIMScript.ps1

PIM command bug fixes

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

added braces for Join-Path

---

src/AzSK.Framework/Helpers/Helpers.ps1

Bug fix for merging empty array objects from policy files

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json

Whitelisting 'MS-PIM' account for PIM control

---

src/AzSK/Framework/Core/AzSKInfo/ControlsInfo.ps1

Fixed issue for GAI -upbc exporting all control list

---

src/AzSK/AlertMonitoring/LogAnalytics.ps1
src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/AzSK/Framework/Core/FixControl/Services/AppServiceFix.ps1
src/OSSConfiguration/ARMControls.json

Bug Fixes :-
1)  ARMChecker: Control properties(Severity, tags) are not in sync with AzSK Services controls
2) LA: Set-AzSKMonitoringSettings not doing a 'css' internally.
3) App Service 'Azure_AppService_BCDR_Use_Multiple_Instances' fix script not working.

Bug Fixes 1908

---

src/AzSK/PIM/PIM.ps1

</br>
Updated common parameter alias in PIM command.

Updated common parameter alias in PIM command

---

src/AzSK.Framework/Listeners/UserReports/WriteEnvironmentFile.ps1
src/AzSK/Framework/Core/AzSKInfo/BasicInfo.ps1
src/AzSK/Framework/Core/AzSKInfo/ControlsInfo.ps1

Bug Fix AzSKInfo 4789134, 4789132

---

src/AzSK/Framework/Core/AzSKInfo/EnvironmentInfo.ps1

Added more separating lines in diff parts of the output of 'gai -it HostInfo' 

---

src/AzSK.Framework/Helpers/ResourceHelper.ps1
src/AzSK/AzSK.psm1
src/AzSK/AzSKStaging.psd1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetupAzureRm.ps1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/FixControl/Services/StorageFix.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/Framework/Core/SVT/Services/Storage.ps1
src/OSSConfiguration/RunbookCoreSetupAzureRm.ps1

Users/nikita/feature update az module to 2.4.0

---

src/AzSK.Framework/Listeners/UserReports/WriteEnvironmentFile.ps1

Bug 4791727

---

src/AzSK.AzureDevOps/Framework/Configurations/AzSk.json
src/AzSK/Framework/Configurations/AzSk.json
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1

Add *** around org-policy message

---

src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1

Made changes in the message displayed for "gai -it ComplianceInfo -upbc"

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

Exception message in case of duplicate automation account

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Fixed GenerateFixScript bug

---

src/AzSK/Framework/Core/FixControl/Services/SQLDatabaseFix.ps1
src/AzSK/Framework/Core/SVT/Services/SQLDatabase.ps1

Suppressed warning of Get-AzSqlServerThreatDetectionPolicy and Get-AzSqlServerAuditing commands

---

src/AzSK/AzSK.psm1
src/AzSK/Framework/Configurations/SVT/Services/SQLDatabase.json
src/AzSK/Framework/Core/FixControl/Services/SQLDatabaseFix.ps1
src/AzSK/Framework/Core/SVT/Services/SQLDatabase.ps1

- Replaced soon to be deprecated Az SQLServer and Az SQLDatabase cmdlet with the new cmdlets.
- Removed 'Enable-AzureRMAlias' from AzSK.psm1

Replaced deprecated Az SQLServer and Az SQLDatabase cmdlet and removed 'Enable-AzureRMAlias' 

---

src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json

1. Updated recommendation of "Azure_Subscription_AuthZ_Limit_ClassicAdmin_Count control.

[Minor Bugfix] Recommendation update.

---

src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/SVT/SVT.ps1

Enable donotopenoutputfolder by default for Org policy cmds

---

src/AzSK/Framework/Core/AzureMonitoring/LogAnalyticsMonitoring.ps1

Bugfix: [IOM] Fixed error handling for Test-AzResourceGroupDeployment command

---

src/AzSK/Framework/Configurations/SVT/Services/AppService.json
src/AzSK/Framework/Configurations/SubscriptionSecurity/Subscription.ARMPolicies.json
src/AzSK/Framework/Core/SVT/Services/AppService.ps1
src/AzSK/Framework/Core/SVT/Services/ERvNet.ps1
src/AzSK/SVT/SVT.ps1

1- App service add telemetry for TLS version
2- ErvNetControl Changes
</br>

Code Changes for ErvNet control and telemetry

---

src/AzSK.Framework/Models/Enums.ps1

Fixed attestation enum issue

---

src/AzSK/Framework/Core/SubscriptionSecurity/ARMPolicies.ps1

-Fixed ValidatePolicyConfiguration: Changed -Erroraction silentlycontinue to Stop
-Fixed Set-AzSKARMPolicy error handling

Bugfix set-azskarmpolicy check

---

src/AzSK/Framework/Core/CredHygiene/CredHygieneScript.ps1

Made DoNotOpenOutputFolder true by default.

---

src/AzSK.Framework/Listeners/RemoteReports/RemoteReportsListener.ps1
src/AzSK/Framework/Configurations/FeatureFlighting.json

Rename for FeatureFlightFlag variable

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/SVT/SVT.ps1

Added trim() to handle space

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

Changed key type from KSP to CSP in SSC generaion

---

src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

bugfix optimized apim urlscheme control's statedata

---

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetup.ps1
src/OSSConfiguration/RunbookCoreSetup.ps1

Added helper schedules

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

corrected typo

---

src/AzSK/Framework/Core/AzSKInfo/BasicInfo.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1

changed message for deprecated account check in GAI SubInfo

---

src/AzSK/Framework/Core/SVT/Services/Search.ps1

Corrected 'Azure_Search_Availability_Configure_Three_Replicas' control error

Corrected 'Azure_Search_Availability_Configure_Three_Replicas' control error

---

src/AzSK.Framework/Abstracts/SVTCommandBase.ps1
src/AzSK.Framework/Helpers/ControlHelper.ps1
src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/Framework/Core/SVT/SVTStatusReport.ps1
src/AzSK/PIM/PIM.ps1

bug fixes for PIM command and control severity switch support in GACS command

---

src/AzSK.AzureDevOps/Framework/Core/SVT/SVTControlAttestation.ps1
src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1

Minor message fix/exception throw behaviour

---

src/AzSK.Framework/Abstracts/CommandBase.ps1
src/AzSK.Framework/Managers/ConfigurationManager.ps1
src/AzSK.Framework/Managers/ControlStateExtension.ps1
src/AzSK/AzSK.psm1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetup.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1

Minor corrections to messages and Org policy bug fixes

---

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetup.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/OSSConfiguration/RunbookCoreSetup.ps1

Added code to link schedule to RB

---

src/AzSK/Framework/Core/InClusterCA/ContinuousAssuranceForDatabricks.ps1

ADB Formatting

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK.Framework/Helpers/ControlHelper.ps1
src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1

Bug fix for -ubc -upbc not scanning any control in case there is no upbc controls defined.
Bug fix for -severity when multiple valid values are passed to parameter

bug fix for -ubc -upbc and -severity

---

src/AzSK.Framework/Helpers/Constants.ps1
src/AzSK.Framework/Managers/ConfigurationManager.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1

Updated messages for IOP and fixed debugging issue

---

src/AzSK/Framework/Core/ARMChecker/ARMCheckerStatus.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/Alerts.ps1

ARM Checker severity issue and alert runbook bug fix

---

src/AzSK/Framework/Listeners/AzListenerHelper.ps1
src/AzSK/Framework/Listeners/AzResourceInventoryListener.ps1

bugfix for incorrect output folder issue

---

src/AzSK.Framework/Helpers/Constants.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1

Minor space changes

---

src/AzSK/Framework/Listeners/AzResourceInventoryListener.ps1

Removed Fetch resource call from constructor

---

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookCoreSetup.ps1
src/OSSConfiguration/RunbookCoreSetup.ps1

Reverted schedules count to 4

---

src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

VM deallocation status Status

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json

added contains for query

---

src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

added else part

---

src/AzSK.AzureDevOps/Framework/Core/SVT/SVTControlAttestation.ps1
src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1

</br>
Changed the messages for exception approval flow as discussed with Manish.

Message updates

---

src/AzSK.Framework/Listeners/FixControl/WriteFixControlFiles.ps1
src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json

</br>
This PR contains fix for:
1- Flag 'GenerateFix' Script not creating service file under fixscript folder.

Bug fix 1909

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

1909 BugFix

---

src/AzSK/Framework/Core/SubscriptionSecurity/ARMPolicies.ps1

Minor comment change

---

src/AzSK.Framework/Listeners/LogAnalytics/LogAnalyticsOutput.ps1
src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json

Details of changes:
1. Added the SignInName property to Owners as well - which was earlier not being populated.
2. A minor case correction for AltWSId
</br>

Bug 4767980 fix

---

src/AzSK/Framework/Core/SVT/SVTResourceResolver.ps1

GRS TagValue fix. Use only tagName if Tagvalue is not provided.

---

src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1

Message added

---

src/AzSK.Framework/Helpers/Constants.ps1
src/AzSK.Framework/Helpers/LogAnalyticsHelper.ps1
src/AzSK/CredHygiene/CredHygiene.ps1
src/AzSK/Framework/Configurations/SubscriptionSecurity/CredentialHygieneAlert_CredentialGroup.json
src/AzSK/Framework/Core/CredHygiene/CredHygieneScript.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

1) Grouping of credentials being tracked, alerts can now be set for each grouped creds.
2) UX improvements for the command output.

Cred hygiene

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/Framework/Helpers/ComplianceReportHelper.ps1
src/AzSK/PIM/PIM.ps1

1) Fix for 'Activate at single rsrc level seems to be failing.'
2) Fix for 'ConvertPermanentAssignmentsToPIM  - The property '$error.code' cannot be found on this object. '
3) Fix for GAI ComplianceInfo Sync command

bug fix 1909 

---

src/AzSK.Framework/Helpers/WebRequestHelper.ps1
src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/PIM/PIM.ps1

1) Added '-ConfigureRoleSettings' switch to update a particular role setting
2) Minor change in the extend expiration logic, if the days for extension exceed maximum allowed assignment limit, the maximum allowed expiry would be taken as the final days of extension
3) Added check for not including inherited permanent accounts

PIM configure role settings changes

---

src/AzSK.Framework/Helpers/ContextHelper.ps1

Removed the hidden special character from ContextHelper.ps1

Removed the hidden special character from ContextHelper.ps1

---

src/AzSK.Framework/Helpers/AIOrgTelemetryHelper.ps1
src/AzSK.Framework/Helpers/ActiveDirectoryHelper.ps1
src/AzSK.Framework/Helpers/IdentityHelpers.ps1
src/AzSK.Framework/Helpers/LogAnalyticsHelper.ps1
src/AzSK.Framework/Helpers/WebRequestHelper.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Helpers/RoleAssignmentHelper.ps1
src/AzSK/PolicySetup/PolicySetup.ps1

Azure US Government - LA & AI

---

src/AzSK/Framework/Core/AzSKInfo/BasicInfo.ps1

Changes for bug #4789129, GAI message changes

Changes for bug #4789129, GAI message changes

---

src/AzSK/Framework/Core/SVT/Services/ERvNet.ps1

ERvNet required arm policies changes

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Core/SVT/Services/AppService.ps1

Updated logic for App Service (Linux) controls

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/OSSConfiguration/ARMControls.json

Added arm controls in App Service, Search & VNet

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/OSSConfiguration/ARMControls.json

container registery control for ARM checker

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/Storage.json
src/AzSK/Framework/Core/FixControl/Services/StorageFix.ps1
src/AzSK/Framework/Core/SVT/Services/Storage.ps1

This change is to Enable "Azure_Storage_Audit_Issue_Alert_AuthN_Req" Control.
It is done  to incorporate Non-classic alerts.
Task:  https://microsoftit.visualstudio.com/OneITVSO/_workitems/edit/4757751

Enabled "Azure_Storage_Audit_Issue_Alert_AuthN_Req" Control

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/PIM/PIM.ps1

minor changes for default values in configure role settings

---

src/AzSK/Framework/Core/ARMChecker/ARMCheckerStatus.ps1
src/AzSK/Framework/Core/SVT/Services/Databricks.ps1

1- ARM Checker Org policy mode
2- Skip PAT prompt for ADB
</br>

Added support for following:

---

src/AzSK.Framework/Helpers/SVTMapping.ps1
src/AzSK/Framework/Configurations/SVT/Services/DBForMySql.json
src/AzSK/Framework/Configurations/SVT/Services/MySql.ps1
src/AzSK/Framework/Core/SVT/Services/DBForMySql.ps1

Added SVT for Azure MySQL service

New SVTs for Azure MySql

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/AppService.json
src/AzSK/Framework/Core/SVT/Services/KubernetesService.ps1
src/OSSConfiguration/ARMControls.json

Updated AKS verison and logic to check latest version

---

src/AzSK/CredHygiene/CredHygiene.ps1
src/AzSK/Framework/Core/CredHygiene/CredHygieneScript.ps1

left alignment

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Updated message in permanent access control

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/OSSConfiguration/ARMControls.json

Disable CORS armchecker rule for storage

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

Contoso CA bug fix

---

src/AzSK/Framework/Configurations/SVT/Services/Storage.json

Disable Azure_Storage_Audit_Issue_Alert_AuthN_Req
