azsk/DevOpsKit

src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

Updated logic for VM control : Check guest config policy health

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Updated message to print expected value type when scanning sub for required tags.

Updated message to print expected value type when scanning sub for required tags.

---

src/AzSK/CredHygiene/CredHygiene.ps1
src/AzSK/Framework/Core/CredHygiene/CredHygieneScript.ps1

Cred hygiene improvements

---

src/AzSK/Framework/Configurations/SVT/Services/DBForPostgreSQL.json

Typo fix in PostgreSQL

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1

bug fix for Role Settings activation and assignment duration

---

src/AzSK/Framework/Core/InClusterCA/ContinuousAssuranceForKubernetes.ps1
src/AzSK/Framework/Framework.ps1
src/AzSK/InClusterCA/ContinuousAssuranceForClustersRoot.ps1

AKS In-Cluster CA integration into main module

---

src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1

Removed attestation details from GAI compliance info result. For attestation details, user can use GAI attestationInfo.

Removed attestation details from GAI compliance info result.

---

src/AzSK/Framework/Core/InClusterCA/ContinuousAssuranceForDatabricks.ps1

more descriptive CA Summary for databricks

---

src/AzSK/Framework/Core/InClusterCA/ContinuousAssuranceForDatabricks.ps1

Fixed suppressed exception

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/Services/AppService.ps1
src/AzSK/Framework/Core/SVT/Services/ERvNet.ps1

Updated control logic for ERvNET LAB instance

---

src/AzSK.Framework/Helpers/Constants.ps1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/KubernetesService.json
src/AzSK/Framework/Core/InClusterCA/ContinuousAssuranceForKubernetes.ps1
src/AzSK/Framework/Core/SVT/Services/KubernetesService.ps1
src/AzSK/InClusterCA/ContinuousAssuranceForClustersRoot.ps1

Added support for LA in AKS In cluster CA and added new control for AKS

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Helpers/LogAnalyticsHelper.ps1
src/AzSK.Framework/Models/Common/ResourceInventory.ps1
src/AzSK/Framework/Listeners/AzResourceInventoryListener.ps1

Updated code to save the resource to tag mapping from ResourceInventory telemetry event and use it to send RG tag details along with scan logs to Log analytics telemetry

Bugfix: 'ComponentId' and 'Env' tags fix

---

src/AzSK/Framework/Configurations/SVT/Services/Storage.json
src/AzSK/Framework/Core/SVT/Services/Storage.ps1

Storage account: 4 new controls

---

src/AzSK.Framework/Helpers/LogAnalyticsHelper.ps1

Bugfix - Updated GetLAWSBodyObjects to check IsResource before mapping resource their respective RG tags.
</br>

Bugfix: Error while sending logs to Log Analytics | Property 'ResourceId' cannot be found

---

src/AzSK/Framework/Helpers/RoleAssignmentHelper.ps1

Fix for bug 5069809

---

src/AzSK/Framework/Configurations/SVT/Services/KubernetesService.json
src/AzSK/InClusterCA/ContinuousAssuranceForClustersRoot.ps1

converted param downloadjoblogs not mandatory

---

src/AzSK/Framework/Core/SVT/Services/Storage.ps1

Storage Network Control attestation fix

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/OSSConfiguration/ARMControls.json

Users/rohit yadav msft/armcontrolchanges

---

src/AzSK/Framework/Helpers/RoleAssignmentHelper.ps1

Rolling back change for CSP subs

---

src/AzSK.Framework/Helpers/WebRequestHelper.ps1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/PIM/PIM.ps1

PIM Changes for 1911

---

src/AzSK/Framework/Configurations/SVT/Services/DataLakeStore.json

Removed special char from recommendation

Removed special char from recommendation

---

src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

Bug Fix VM Guest Config control enable MSI

---

src/AzSK.Framework/Listeners/UserReports/WritePsConsole.ps1
src/AzSK/Framework/Core/InClusterCA/ContinuousAssuranceForHDInsight.ps1

change Sort to Sort-Object

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/APIManagement.json
src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

APIM TLS control

---

src/AzSK/Framework/Configurations/SVT/Services/AppService.json

Renamed App Service TLS control

---

src/AzSK.Framework/Helpers/RemoteReportHelper.ps1
src/AzSK.Framework/Models/RemoteReports/ScanResultModels.ps1

</br>
Added the field to send the Attestation expiry date o the Scan results API to insert the data to the DB.

Sending AttestationExpiryDate to API

---

src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/Framework/Helpers/ResourceHelper.ps1

Org policy changes to support PSCore

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1

bug fix: added try catch block to check if authorization denied

bug fix: added try catch block to check if authorization denied

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1

ASC pricing tier metadata + MG level skip logic

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/AllResourceTypes.json
src/AzSK.Framework/Helpers/SVTMapping.ps1
src/AzSK/AzSK.pssproj
src/AzSK/AzSKStaging.psd1
src/AzSK/Framework/Configurations/AzSKInfo/CategoryMapping.json
src/AzSK/Framework/Configurations/SVT/AllResourceTypes.json
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/VirtualMachineScaleSet.json
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1
src/AzSK/Framework/Core/SVT/Services/VirtualMachineScaleSet.ps1

Added controls for VM Scale Sets

---

src/AzSK/Framework/Core/SVT/Services/Storage.ps1

Storage Network control attestation statedata

---

src/AzSK/Framework/Configurations/SVT/Services/VirtualMachineScaleSet.json
src/AzSK/Framework/Core/SVT/Services/VirtualMachineScaleSet.ps1

Fixed bug related to no instances in VMSS

---

src/AzSK/Framework/Core/SVT/Services/ContainerInstances.ps1

</br>
To make sure correct resource type is picked up in case of multiple resources with same names.

ContainerInstances bug fix

---

src/AzSK/Framework/Core/SVT/Services/VirtualMachineScaleSet.ps1

Added silently continue on error state

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/OSSConfiguration/ARMControls.json

Renamed App Service control in ARM Checker as well

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/OSSConfiguration/ARMControls.json

Updated severity for TLS version in ARM Checker

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/AzSK/Framework/Configurations/SVT/Services/AppService.json
src/OSSConfiguration/ARMControls.json
src/OSSConfiguration/ControlSettings.json

Renamed App Service control

---

src/AzSK/Framework/Core/PolicySetup/AzSKStaging-EasyInstaller.ps1
src/AzSK/Framework/Core/PolicySetup/EasyInstaller.ps1

IWR changes to enable TLS 1.2

---

src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json

Excluded VM controls for AKS & ADB cluster

---

src/AzSK/Framework/Configurations/SVT/Services/AppService.json
src/AzSK/Framework/Core/FixControl/Services/AppServiceFix.ps1
src/AzSK/Framework/Core/SVT/Services/AppService.ps1

Added support for Auto-Fix in control : Azure_AppService_DP_Use_Secure_TLS_Version

---

src/AzSK/Framework/Core/InClusterCA/ContinuousAssuranceForDatabricks.ps1

Have update databricks scan job to edit instead of delete and reupload

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/VirtualMachineScaleSet.json
src/AzSK/Framework/Core/SVT/Services/VirtualMachineScaleSet.ps1

Added new VMSS control and Updated latest supported AKS versions

---

src/AzSKPy/azskpy/kubernetescontrols.py
src/AzSKPy/azskpy/main.py

Added new controls for AKS In-cluster CA

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/OSSConfiguration/ARMControls.json

VMSS ARM Checker controls for new SVTs

---

src/AzSK/Framework/Abstracts/AzSVTBase.ps1

Logic modification based on new metric alerts for below controls
'Azure_APIManagement_Audit_Enable_Alerts, 
Azure_Batch_Audit_Enable_Metric_Alert,
Azure_StreamAnalytics_Audit_Issue_Alert_Runtime_Errors_Failed_Functions'

Metric alert changes for Batch, APIM, StreamAnalytics

---

src/AzSK.Framework/Helpers/SVTMapping.ps1
src/AzSK/Framework/Configurations/SVT/Services/LogAnalytics.json
src/AzSK/Framework/Core/SVT/Services/LogAnalytics.ps1

1. Added SVT controls for Log Analytics workspace
2. Updated SVT Mapping file

Log analytics SVT controls

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Helpers/Constants.ps1

Global Variable Exist check

---

src/AzSK.Framework/Abstracts/SVTCommandBase.ps1

Bug fix: GSS Error in attestation

---

src/AzSK/Framework/Configurations/SVT/Services/LogAnalytics.json
src/AzSK/Framework/Core/SVT/Services/LogAnalytics.ps1

Updated CheckLinkedAutomationAccountSPNsRBAC function

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Handling condition for attested results

---

src/AzSK/Framework/Core/SVT/Services/LogAnalytics.ps1

Corrected control logic

---

src/AzSK/Framework/Core/PolicySetup/AzSKStaging-EasyInstaller.ps1
src/AzSK/Framework/Core/PolicySetup/EasyInstaller.ps1

Revert TLS Changes

---

src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Added deallocation check for VM ASC controls

---

src/AzSK.Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK/Framework/Configurations/FeatureFlighting.json

removing resource scan tracker event

---

src/AzSK/Framework/Configurations/SVT/Services/LogAnalytics.json
src/AzSK/Framework/Core/SVT/Services/LogAnalytics.ps1

Log analytics: Updated control id, control's function name and tags

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1

Bug fix for PIM soon to expire

---

src/AzSK.Framework/Models/Enums.ps1
src/AzSK/SVT/SVT.ps1

BugFix for GeneratePDF switch None as parameter not required

---

src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/Framework/Core/SVT/Services/SQLDatabase.ps1

Bug fixes for SQL Audit and Threat detection control

---

src/AzSK.Framework/Abstracts/CommandBase.ps1

Bug Fix: Open output folder after rescan is complete for attested controls

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Subscription lock details: Remove notes and name 

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/PIM/PIM.ps1

Bug fix for typo and enabling MFA on activation

---

src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

Linux VM Antimalware control is erroring out fixed

---

src/AzSK.Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK.Framework/Managers/PartialScanManager.ps1
src/AzSK/Framework/Configurations/FeatureFlighting.json

Persist storage blob per resource - large subs CA

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json

max object count for resource inventory

---

src/AzSK.Framework/Abstracts/CommandBase.ps1
src/AzSK.Framework/Helpers/AIOrgTelemetryHelper.ps1
src/AzSK.Framework/Helpers/RemoteApiHelper.ps1

Bom Char issue 

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/APIManagement.json
src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

- Fixed stream issue
- Added a check for number of APIs in an APIM service
</br>

APIM large sub fixes

---

src/AzSK.Framework/Abstracts/CommandBase.ps1

Fix for AttestationValue variable not found in CA

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

Added new checks in GCA for suspended job and large subs

---

src/AzSK/Framework/Core/SVT/Services/ServiceBus.ps1

1. Fixed Azure_ServiceBus_AuthZ_Use_Minimum_Access_Policies

Fixed Azure_ServiceBus_AuthZ_Use_Minimum_Access_Policies

---

src/AzSK/Framework/Core/SVT/Services/SQLDatabase.ps1

1. Added error handling for SQLAudit command.
_Expected result:_
_Control should return Verify state if storage account is not found._
2. Removed function 'IsServerThreatDetectionEnabled()' as it was not being used anywhere in the DevOps kit code.
</br>

SQLDatabase SVT control error bugfix

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

fixing the build issue

---

src/AzSK/Framework/Listeners/AzResourceInventoryListener.ps1

Bug fix for resourceInventory limiting to only scannable resources

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

Updated the messgaes for GCA changes.

---

src/AzSK.Framework/Helpers/AIOrgTelemetryHelper.ps1
src/AzSK.Framework/Helpers/RemoteApiHelper.ps1

BOM char fix for ResourceFlat API

---

src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json
src/OSSConfiguration/ARMControls.json

Azure_AppService_Deploy_Use_Latest_Version

---

src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/SVT/SVTIaasBase.ps1

changed the severity of control and minor fix

---

src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

Corrected variable name in APIManagement.ps1

---

src/AzSK/Framework/Core/SVT/SVTIaasBase.ps1

Bug fix for NICs with more than one IpConfigurations not getting listed

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Configurations/SVT/ControlSettings.json

Adding vNet feature flag

---

src/AzSK.Framework/Abstracts/CommandBase.ps1
src/AzSK.Framework/Models/Enums.ps1
src/AzSK/SVT/SVT.ps1

Generate pdf fix for express route and GCS

---

src/AzSK/Framework/Core/SVT/SVTIaasBase.ps1

Rolling back Vnet changes

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.AgentPool.json
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.AgentPool.ps1

Added control to agt pool grant all pipe access

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Project.json
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Project.ps1

project control review comment fixed

---

src/AzSK/Framework/Core/SVT/Services/AppService.ps1
src/AzSK/Framework/Core/SVT/Services/ERvNet.ps1
src/AzSK/Framework/Core/SVT/Services/VirtualNetwork.ps1

App Service & vNet control fix

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/PIM/PIM.ps1

PIM: API changes for Role Settings

---

src/AzSK/Framework/Core/SVT/Services/ServiceFabric.ps1

Bugfix: Service fabric 'BackendIpConfigurations' cannot be found on this object

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.AgentPool.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Build.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Release.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.ServiceConnection.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Organization.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Project.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK.AzureDevOps/Framework/Helpers/CommandHelper.ps1
src/AzSK.AzureDevOps/Framework/Helpers/LogAnalyticsHelper.ps1
src/AzSK.AzureDevOps/Framework/Listeners/UserReports/WriteSummaryFile.ps1
src/AzSK.AzureDevOps/SVT/SVT.ps1

Dev ops kit for x/ado

---

src/AzSK.AzureDevOps/Framework/Core/SVT/SVTResourceResolver.ps1

organization with wrong name issue fixed

---

src/AzSK.AzureDevOps/Framework/Helpers/Constants.ps1
src/AzSK.AzureDevOps/Framework/Listeners/UserReports/WritePsConsole.ps1
src/AzSK.AzureDevOps/Framework/Listeners/UserReports/WriteSummaryFile.ps1

Dev ops kit for x/ado resource link change

---

src/AzSK.AzureDevOps/Framework/Listeners/UserReports/WriteSummaryFile.ps1

added agent pool in resourcelink

---

src/AzSK/Framework/Core/SVT/SVTIaasBase.ps1
src/AzSK/Framework/Core/SVT/Services/ERvNet.ps1
src/AzSK/Framework/Core/SVT/Services/VirtualNetwork.ps1

1) Removed Get-AzResource calls while creating base object for fetching VM and NSG.
2) Instead of adding all NICS object in log files and control state for Justify PublicIp control, now the NICS with have public Ip addresses attached to them would be added.

Virtual Network SVT object optimization

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/PIM/PIM.ps1

PIM: Remove existing role assignment

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

APIM enhancements

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1

PIM List commands output an csv

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.AzureDevOps/Framework/Core/SVT/SVTResourceResolver.ps1

ADO (incorrect orgnization scane display proper msg, preview baseline control fix)

---

src/AzSK/AzSK.psm1

Removed extra folder 

---

src/AzSK/AzSK.psm1
src/AzSK/Framework/Configurations/FeatureFlighting.json

Develop to Master

---

src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/FixControl/Services/SubscriptionCoreFix.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenterStatus.ps1
src/AzSK/SubscriptionSecurity/SecurityCenter.ps1
src/OSSConfiguration/ControlSettings.json

ASC control refactor changes

---

src/AzSK/Framework/Core/CAwithACI/ContinuousAssurance.ps1

Printing fn app name on console

---

src/AzSK/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK/Framework/Core/CAwithACI/ContinuousAssurance.ps1

ICA bug fix & making -Usecontainers available only for CSE org

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1

Removed hidden chararcters : Conditional Access message

---

src/AzSK/Framework/Core/InClusterCA/ContinuousAssuranceForDatabricks.ps1

Bug fix Install CA - ADB

---

src/AzSK/Framework/Core/SVT/Services/ERvNet.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

ErVnet control status bug

---

src/AzSK/Framework/Core/SubscriptionSecurity/ARMPolicies.ps1

Corrected SetPolicyInitiative function to update the initiative if already exists

Corrected SetPolicyInitiative function to update the initiative if already exists

---

src/AzSK.Framework/Listeners/UserReports/WritePsConsole.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

bug fix short command error

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json

Modified linux anit-malware query

---

src/AzSK.AzureDevOps/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK.AzureDevOps/Framework/Listeners/UserReports/WriteSummaryFile.ps1
src/AzSK.AzureDevOps/Framework/Models/RemoteReports/CsvOutputModel.ps1

migration (resourcelink changes)

---

src/AzSK/Framework/Core/SVT/Services/AppService.ps1
src/AzSK/Framework/Core/SVT/Services/ServiceFabric.ps1

App svc control changes and SF bug fix

---

src/AzSK/AzSK.psm1
src/AzSK/AzSKStaging.psd1
src/AzSK/Framework/Configurations/SVT/Services/SQLDatabase.json
src/AzSK/Framework/Core/FixControl/Services/SQLDatabaseFix.ps1
src/AzSK/Framework/Core/SVT/Services/AppService.ps1
src/AzSK/Framework/Core/SVT/Services/NotificationHub.ps1
src/AzSK/Framework/Core/SVT/Services/SQLDatabase.ps1
src/AzSK/Framework/Core/SVT/Services/ServiceFabric.ps1
src/AzSK/Framework/Helpers/SecurityCenterHelper.ps1

Az Modules Upgrade

---

src/AzSK.Framework/Abstracts/CommandBase.ps1
src/AzSK.Framework/Models/AzSKSettings.ps1
src/AzSK/AzSK.psm1

SAW- Module autoupdate fix

---

src/AzSK/PIM/PIM.ps1

Bug Fix for parameter set

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1

code changes for control Azure_Subscription_Config_ASC_Tier

---

src/AzSK/Framework/Abstracts/AzSVTBase.ps1
src/AzSK/Framework/Configurations/SVT/Services/AppService.json
src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json

Bugfix for the issues identified in azure policy compliance check

---

src/AzSK/AzSK.psm1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

Fixed CA issues on SAW

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/PIM/PIM.ps1

Removed feature flight and resolved Configure role settings parameters

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/ControlSettings.json

control setting small change

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1
src/AzSK/PIM/PIM.ps1

Changes for ASC SecuritySolutions in metadata,PIM bug fix and CA SPN default permission bug fix

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1

Removed CA policy tagname input from setpim command

---

src/OSSConfiguration/ControlSettings.json

OSS Baseline controls sync

---

src/AzSK.Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1

ASC and GXX FilterTags Bug fix

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Core/SubscriptionSecurity/ARMPolicies.ps1

Create separate feature flight flags for "EnableAzurePolicyBasedScan"

---

src/AzSK/Framework/Configurations/SVT/Services/APIManagement.json
src/AzSK/Framework/Configurations/SVT/Services/AppService.json
src/AzSK/Framework/Configurations/SVT/Services/CloudService.json
src/AzSK/Framework/Configurations/SVT/Services/CosmosDB.json
src/AzSK/Framework/Configurations/SVT/Services/DBForMySql.json
src/AzSK/Framework/Configurations/SVT/Services/DBForPostgreSQL.json
src/AzSK/Framework/Configurations/SVT/Services/DataLakeStore.json
src/AzSK/Framework/Configurations/SVT/Services/HDInsight.json
src/AzSK/Framework/Configurations/SVT/Services/KubernetesService.json
src/AzSK/Framework/Configurations/SVT/Services/LogicApps.json
src/AzSK/Framework/Configurations/SVT/Services/RedisCache.json
src/AzSK/Framework/Configurations/SVT/Services/SQLDatabase.json
src/AzSK/Framework/Configurations/SVT/Services/ServiceFabric.json
src/AzSK/Framework/Configurations/SVT/Services/Storage.json
src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json
src/AzSK/Framework/Configurations/SVT/Services/VirtualMachineScaleSet.json

Adding NetSec tag in controls

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/PIM/PIM.ps1

</br>
- Changes for Management Group Configure Role settings
- List Role settings of role

PIM (MGrp role settings, ListRolesettings)

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1

Approved Exception Bug fix

---

src/AzSK.Framework/Models/Enums.ps1
src/AzSK/AzSKStaging.psd1
src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/PIM/PIM.ps1

PIM assignrole for "active" assignmenttype

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1

</br>
Bug Fixes:
- ASC policy assignment BUg fix moved in feature flight
- Message change in Control if PIM is not onboarded in subscription

PIM, PolicyAssignment Bug fix

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK/PIM/PIM.ps1

ApprovedException Expirydate null, PIM bug fix

---

src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Organization.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/SVTControlAttestation.ps1

attestation permission msg change and or msg changes.

---

src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Organization.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Project.ps1

set state data for org/project controls

---

src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Organization.ps1

added state data fpor installed ext control

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Organization.json
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Organization.ps1

removed state capture for extension controls

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Build.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Organization.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Project.json
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Build.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Organization.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Release.ps1

updated state data format

---

src/AzSK.Framework/Models/AzSKSettings.ps1

added azsksettings null check

---

src/AzSK.Framework/Abstracts/CommandBase.ps1
src/AzSK.Framework/Abstracts/SVTCommandBase.ps1
src/AzSK.Framework/Managers/ControlStateExtension.ps1
src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/Framework/Core/SVT/Services/AppService.ps1
src/AzSK/Framework/Core/SVT/Services/Storage.ps1
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Removing feature flag

---

src/AzSK/Framework/Core/SubscriptionSecurity/ARMPolicies.ps1

Fix for checking if ARM policy is actually enfored

---

src/AzSK/Framework/Core/SubscriptionSecurity/ARMPolicies.ps1

Bug fix for SAP command for policyassignment

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/PIM/PIM.ps1

PIM CRS for active assignment type

---

src/AzSK/Framework/Abstracts/AzSVTCommandBase.ps1

Message typo fix

---

src/AzSK.Framework/Models/SVT/AttestationOptions.ps1
src/AzSK/Framework/Abstracts/AzSVTCommandBase.ps1
src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1
src/AzSK/SVT/SVT.ps1

</br>
To accept approved exception expiry date as input

Approved Exception POC

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Organization.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK.AzureDevOps/SVT/SVT.ps1
src/AzSK.Framework/Models/AzSKSettings.ps1

Ccontrol Settings.json trimming, Mandatory cmd param, attestation in individual cmd

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.AgentPool.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Build.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Organization.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Project.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Release.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.ServiceConnection.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.User.json

control scrub

---

src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Build.ps1

[ADO] fixed AzureDevOps_Build_AuthZ_Disable_Inherited_Permissions control

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1
src/AzSK/PIM/PIM.ps1

CRS, approved exp bug fix

---

src/AzSK/SVT/SVT.ps1

Making ControlId mandatory for ApprovedException

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/AppService.json
src/AzSK/Framework/Core/SVT/Services/AppService.ps1
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

Updated VM guest config policy control and new App Svc AAD auth control

---

src/AzSK.AzureDevOps/Framework/Abstracts/ADOSVTBase.ps1
src/AzSK.AzureDevOps/Framework/Configurations/ADOAttestation.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Build.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/SVTControlAttestation.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK.AzureDevOps/Framework/Helpers/Constants.ps1
src/AzSK.AzureDevOps/Framework/Managers/ControlStateExtension.ps1
src/AzSK.AzureDevOps/SVT/SVT.ps1

[ADO] Attestation code changes

---

src/AzSK.AzureDevOps/Framework/Managers/ControlStateExtension.ps1

Update ext stotrage msg

---

src/AzSK.AzureDevOps/AzSKStaging.AzureDevOps.psd1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.AgentPool.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Build.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Organization.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Release.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.ServiceConnection.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK.AzureDevOps/Framework/Managers/ControlStateExtension.ps1

control state data

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/Services/AppService.ps1

Updated App Svc + AKS image path

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.User.json
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Project.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.User.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/SVTControlAttestation.ps1
src/AzSK.AzureDevOps/Framework/Managers/ControlStateExtension.ps1

msg updates + prj visibility control logic update

---

src/AzSK.AzureDevOps/AlertMonitoring/LogAnalytics.ps1
src/AzSK.AzureDevOps/AzSK.AzureDevOps.psm1
src/AzSK.AzureDevOps/AzSKStaging.AzureDevOps.psd1
src/AzSK.AzureDevOps/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK.AzureDevOps/Framework/Helpers/CommandHelper.ps1

set lognalytics enabled

---

src/AzSK.AzureDevOps/SVT/SVT.ps1

Minor, test.

---

src/AzSK/Framework/Core/SVT/SVTIaasBase.ps1

VNetLargeSubFix

---

src/AzSK/Framework/Core/SVT/Services/CosmosDb.ps1

Changes to add API version to avoid control getting into error- Azure_CosmosDB_AuthZ_Enable_Firewall Azure_CosmosDB_AuthZ_Verify_IP_Range

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/PIM/PIM.ps1

CA RG control, Listrolesettings MGrp changes

---

src/AzSK.Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK.Framework/Listeners/RemoteReports/AIOrgTelemetry.ps1
src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1
src/AzSK/Framework/Helpers/AzHelper.ps1
src/AzSK/Framework/Helpers/RoleAssignmentHelper.ps1

Removing "EnableASCPolicyOnVMCheckUsingPolicyAssessmentKey" feature flag

---

src/AzSK.Framework/Abstracts/ServicesSecurityStatus.ps1

ServiceSecurityStatus Policy modification

---

src/AzSK/Framework/Configurations/SVT/Services/APIManagement.json
src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

APIM Bug fix for 3443 port restriction and Consumption tier

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/Services/KeyVault.json
src/AzSK/Framework/Core/SVT/Services/AppService.ps1
src/AzSK/Framework/Core/SVT/Services/CosmosDb.ps1
src/AzSK/Framework/Core/SVT/Services/KeyVault.ps1

KeyVault And App Service changes for External customer request

---

src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Build.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Organization.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Release.ps1

control bug fixes

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.AgentPool.json
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Organization.ps1

ADO resolved confict

---

src/AzSK/Framework/Configurations/SVT/Services/ERvNet.json

Updating json properties to prevent attestation drift

---

src/AzSK.AzureDevOps/Framework/Managers/PartialScanManager.ps1

UPC bug fix

---

src/AzSK.AzureDevOps/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK.AzureDevOps/SVT/SVT.ps1

resolver for null projects and refinements

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

PIM Role assignment NextLink

---

src/AzSK/Framework/Core/SVT/Services/AppService.ps1

[AzSK] Correction in message for detailed log file

---

src/AzSK/Framework/Configurations/SVT/Services/DataFactory.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

[DataFactory] Spell correction done in Data Factory SVT control name

---

src/AzSK/Framework/Core/SVT/Services/AppService.ps1

AppService : Tag added [HasRequiredAccess]

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Abstracts/SVTCommandBase.ps1
src/AzSK.Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK.Framework/Helpers/Constants.ps1
src/AzSK.Framework/Helpers/LogAnalyticsHelper.ps1
src/AzSK.Framework/Listeners/LogAnalytics/LogAnalyticsOutput.ps1
src/AzSK.Framework/Listeners/UserReports/WriteSummaryFile.ps1
src/AzSK.Framework/Models/RemoteReports/CsvOutputModel.ps1
src/AzSK/Framework/Abstracts/AzCommandBase.ps1
src/AzSK/Framework/Configurations/AlertMonitoring/AZSK.AM.LogAnalytics.GenericView.V3.lawsview
src/AzSK/Framework/Configurations/AlertMonitoring/AZSK.AM.LogAnalytics.GenericView.V4.lawsview
src/AzSK/Framework/Configurations/AlertMonitoring/AZSK.AM.LogAnalytics.GenericView.V5.lawsview
src/AzSK/Framework/Configurations/AlertMonitoring/AZSK.AM.LogAnalytics.GenericView.V6.lawsview
src/AzSK/Framework/Configurations/AlertMonitoring/AZSK.AM.OMS.GenericView.V5.omsview
src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1
src/AzSK/Framework/Core/AzSKInfo/PersistedStateInfo.ps1
src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1
src/AzSK/Framework/Core/SVT/Services/KeyVault.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1
src/AzSK/Framework/Helpers/ComplianceReportHelper.ps1
src/AzSK/Framework/Listeners/CA/WriteCAStatus.ps1

Compliance table dependency removal changes + CA COMP status changes- no applicable/enabled controls

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1

PIM bugfix : Multiple eligible assignments at same scope

---

src/AzSK/Framework/Core/SVT/Services/KeyVault.ps1

Key Vault Owner Access Control Changes

---

src/AzSK/Framework/Configurations/SVT/Services/CDN.json
src/AzSK/Framework/Configurations/SVT/Services/Databricks.json
src/AzSK/Framework/Configurations/SVT/Services/KeyVault.json

Sanitizing Json where invalid chars were introduced

---

src/AzSK.AzureDevOps/Framework/Abstracts/ADOSVTBase.ps1
src/AzSK.AzureDevOps/Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/SVTControlAttestation.ps1
src/AzSK.AzureDevOps/Framework/Helpers/Constants.ps1
src/AzSK.AzureDevOps/Framework/Managers/ControlStateExtension.ps1
src/AzSK.Framework/Abstracts/CommandBase.ps1
src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Abstracts/SVTCommandBase.ps1

[ADO]: Rescan post attestation

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.AgentPool.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Organization.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Project.json
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Organization.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Project.ps1

ubc review

---

src/AzSK.AzureDevOps/Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/SVTResourceResolver.ps1

ScanAllArtifacts should scan all artifacts within the targeted projects

---

src/AzSK.Framework/Abstracts/SVTCommandBase.ps1
src/AzSK.Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK/Framework/Abstracts/AzCommandBase.ps1
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1
src/AzSK/Framework/Core/AzSKInfo/PersistedStateInfo.ps1
src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1
src/AzSK/Framework/Helpers/ComplianceReportHelper.ps1
src/AzSK/Framework/Listeners/CA/WriteCAStatus.ps1

Changes to enable compliance state flag

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Configurations/SVT/Services/ERvNet.json
src/AzSK/Framework/Core/SVT/Services/ERvNet.ps1

Vnet changes for multi nic issue

---

src/AzSK.AzureDevOps/Framework/Helpers/ContextHelper.ps1

UT changes

---

src/AzSK.AzureDevOps/AzSKStaging.AzureDevOps.psd1

ADO: added az.con, az.opin, az.res in module 

---

src/SecureAzureDevOpsExtension/ADOSecurityScanner_Task/ADOSecurityScannerSVTRuntime.ps1
src/SecureAzureDevOpsExtension/ADOSecurityScanner_Task/task.json
src/SecureAzureDevOpsExtension/vss-extension.json

ADO Ext: changes for upc

---

src/AzSK.AzureDevOps/Framework/Helpers/Constants.ps1
src/AzSK.AzureDevOps/Framework/Managers/PartialScanManager.ps1

ADO: partial scan using extension storage

---

src/SecureAzureDevOpsExtension/ADOSecurityScanner_Task/ADOSecurityScannerSVTRuntime.ps1

ADO: extension long running scan, alt oms

---

src/AzSK/Framework/Abstracts/AzSVTBase.ps1
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1
src/AzSK/Framework/Core/AzSKInfo/PersistedStateInfo.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

GAI fixes+ MaximumAllowedGraceDays fixes

---

src/AzSK.AzureDevOps/Framework/Helpers/Constants.ps1

updated UT app insights key

---

src/AzSK/Framework/Core/AzSKInfo/SPNInfo.ps1

Adding message changes and property check

---

src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json

Fix Attestation Drift

---

src/AzSK.AzureDevOps/AzSKStaging.AzureDevOps.psd1

removed Az dependency

---

src/AzSK/Framework/Core/AzSKInfo/SPNInfo.ps1

Adding minor changes to filter AzSDK_CA* SPNs also

---

src/AzSK/Framework/Core/SVT/Services/PublicIpAddress.ps1

Changes for attested state data

---

src/AzSK.Framework/Helpers/SVTMapping.ps1
src/AzSK/Framework/Configurations/SVT/Services/PublicIpAddress.json

Attestation bug fix

---

src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1

Refactored the code

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

CARGcontrol to scan only in CA mode

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Abstracts/SVTCommandBase.ps1
src/AzSK.Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK/Framework/Abstracts/AzCommandBase.ps1
src/AzSK/Framework/Abstracts/AzSVTCommandBase.ps1
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1
src/AzSK/Framework/Core/AzSKInfo/PersistedStateInfo.ps1
src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1
src/AzSK/Framework/Helpers/ComplianceReportHelper.ps1
src/AzSK/Framework/Listeners/CA/WriteCAStatus.ps1

perf improvement changes

---

src/AzSK.AzureDevOps/Framework/BugLog/AutoBugLog.ps1

typo fixed

---

src/AzSK.AzureDevOps/Framework/Managers/PartialScanManager.ps1

Partial commit change

---

src/AzSK.Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Abstracts/AzSVTBase.ps1
src/AzSK/Framework/Core/AzSKInfo/ComplianceInfo.ps1
src/AzSK/Framework/Core/AzSKInfo/PersistedStateInfo.ps1

BugFix for ComplianceInfo not working if RG tag is added

---

src/AzSK/Framework/Core/AzSKInfo/SPNInfo.ps1

Adding Message

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/SVTResourceResolver.ps1

PublicIPBugFix

---

src/AzSK.AzureDevOps/Framework/BugLog/AutoCloseBugManager.ps1
src/AzSK.AzureDevOps/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.AzureDevOps/Framework/Helpers/AdministratorHelper.ps1

admin helper sanitization plus maxsearchquery change

---

src/AzSK.AzureDevOps/Framework/Core/SVT/SVTControlAttestation.ps1
src/AzSK.AzureDevOps/Framework/Managers/ControlStateExtension.ps1
src/AzSK.Framework/Listeners/UserReports/WriteDetailedLog.ps1
src/AzSK.Framework/Models/SVT/SVTEvent.ps1

handle accented chars

---

src/AzSK.Framework/Abstracts/SVTCommandBase.ps1
src/AzSK.Framework/Managers/ControlStateExtension.ps1

Minimised ResourceIndex file calls

---

src/AzSK/Framework/Core/PIM/PIMScript.ps1
src/AzSK/PIM/PIM.ps1

PIM extendexpiringassignments bug fix

---

src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1

Excluded ADE controls for VM with ephemeral disk

---

src/AzSK.Framework/Helpers/Helpers.ps1

Fix for Bom/special char

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

</br>
Azure_Subscription_Configure_Conditional_Access_for_PIM
Azure_Subscription_Configure_Conditional_Access_for_PIM_RG
Azure_Subscription_Use_Only_Alt_Credentials

PIM subs control error handling

---

src/AzSK.Framework/Helpers/RemoteReportHelper.ps1
src/AzSK.Framework/Listeners/RemoteReports/UsageTelemetry.ps1
src/AzSK.Framework/Listeners/UserReports/WriteDataFile.ps1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json

Performance update + OSS telemetry changes 

---

src/AzSK.Framework/Managers/ControlStateExtension.ps1
src/AzSK/Framework/Configurations/FeatureFlighting.json

Fix for fetching control state by resource id

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Abstracts/SVTCommandBase.ps1
src/AzSK.Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK.Framework/Listeners/UserReports/WriteSummaryFile.ps1
src/AzSK.Framework/Models/RemoteReports/CsvOutputModel.ps1
src/AzSK.Framework/Models/SVT/SVTEvent.ps1

Bug Fix: IsControlInGrace to be shown in CSV report if compliance state caching is enabled
</br>

Bug Fix: IsControlInGrace to be shown in CSV report if compliance state caching is enabled

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SubscriptionSecurity/SecurityCenter.json
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1
src/AzSK/Framework/Helpers/SecurityCenterHelper.ps1

Changes for ASC Security Contact

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/SVT/Services/CDN.ps1

Changed CA status to warning

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1

Users/ritika mft/asc changes

---

src/AzSK.Framework/Managers/ControlStateExtension.ps1
src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/Services/AppService.ps1
src/AzSK/Framework/Listeners/CA/WriteCAStatus.ps1

Trim attestation file for deleted resources

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Helpers/ConfigOverride.ps1
src/AzSK.Framework/Helpers/ConfigurationHelper.ps1
src/AzSK.Framework/Managers/ConfigurationManager.ps1
src/AzSK/Framework/Abstracts/AzSVTBase.ps1

Code Optimisation related changes
</br>

Code Optimisation

---

src/AzSK.Framework/Managers/ControlStateExtension.ps1

message changes

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.Framework/Helpers/RemoteReportHelper.ps1
src/AzSK.Framework/Listeners/RemoteReports/UsageTelemetry.ps1
src/AzSK.Framework/Listeners/UserReports/WriteDataFile.ps1

Anon Ut changes

---

src/AzSK.AzureDevOps/AzSK.AzureDevOps.psm1
src/AzSK.AzureDevOps/AzSKStaging.AzureDevOps.psd1
src/AzSK.AzureDevOps/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK.AzureDevOps/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.AzureDevOps/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Build.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Release.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.User.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/Resolver.ps1
src/AzSK.AzureDevOps/Framework/Framework.ps1
src/AzSK.AzureDevOps/Framework/Helpers/CommandHelper.ps1
src/AzSK.AzureDevOps/Framework/Helpers/ContextHelper.ps1
src/AzSK.Framework/Abstracts/CommandBase.ps1

ADO: Continuous Assurance

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.Framework/Listeners/UserReports/WriteDataFile.ps1

GenerateSecurityEvaluationJsonFile change

---

src/AzSK.AzureDevOps/Framework/Core/ContinuousAssurance/CAAutomation.ps1

ADO: CA custommessage

---

src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

SC-ALT control: attestation state data fix

SC-ALT control: attestation state data fix

---

src/AzSK.Framework/Listeners/UserReports/WriteDataFile.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1

Org policy message changes+write date file bug fix

---

src/AzSK.Framework/Listeners/RemoteReports/UsageTelemetry.ps1
src/AzSK.Framework/Managers/ControlStateExtension.ps1

Reader check for trim attestation+ review fixes

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1

Changes for metadata foe security contact control

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SecurityCenter.ps1

Added try catch to handle exception

---

src/AzSK.AzureDevOps/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK.AzureDevOps/Framework/Core/ADOMonitoring/LogAnalyticsMonitoring.ps1
src/AzSK.AzureDevOps/Framework/Core/ContinuousAssurance/CAAutomation.ps1

LA-view, avoid DisconnectAz.
Out-null issue.
AppSettingsHT-add-or-update.
</br>

Resolver orgName bug. LA View avoid Disconnect-Az. CA out-null issue. AppSettings add-or-update issue.

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.AgentPool.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Build.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Organization.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Project.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Release.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.ServiceConnection.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Build.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Organization.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Project.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Release.ps1

Control JSON and baseline list updates

---

src/AzSK/Framework/Configurations/FeatureFlighting.json

updating FF false functionApp kind match

---

src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Revert attestation changes - Check if subset check

---

src/AzSK.AzureDevOps/Framework/Core/AzSKADOInfo/ControlsInfo.ps1
src/AzSK.AzureDevOps/Framework/Core/AzSKADOInfo/HostInfo.ps1
src/AzSK.Framework/Helpers/ConfigurationHelper.ps1

Fix for ambiguous method error in GADI.

---

src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Release.ps1

releas control fix

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Build.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Release.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK.Framework/Abstracts/CommandBase.ps1
src/AzSK.Framework/Helpers/ConfigurationHelper.ps1

Removed redundant regexes, commented them. Added compilation upon first download of ControlSettings.
Can be tested using:
gads -OrganizationName 'safetitestvso' -ProjectNames 'BuildWebAppDemo' -BuildNames '*' -ControlIds 'AzureDevOps_Build_DP_No_PlainText_Secrets_In_Definition, AzureDevOps_Build_SI_Review_URL_Variables_Settable_At_Queue_Time'

RegEx minimize list, comments, compile.

---

src/AzSK/Framework/Core/SVT/Services/CDN.ps1

Azure_CDN_DP_Enable_Https Bug fix

---

src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Alt_Cred control fix

---

src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json

SC-ALT control: Updated recommendation

---

src/AzSK.ADO/Framework/Abstracts/ADOSVTBase.ps1
src/AzSK.ADO/Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK.ADO/Framework/Core/AzSKADOInfo/ControlsInfo.ps1
src/AzSK.ADO/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK.ADO/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK.ADO/Framework/Helpers/SVTMapping.ps1
src/AzSK.ADO/SVT/SVT.ps1
src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK.Framework/Listeners/FixControl/WriteFixControlFiles.ps1
src/AzSK.Framework/Listeners/UserReports/WriteSummaryFile.ps1
src/AzSK.Framework/Models/Common/ResourceInventory.ps1

</br>
Enabled ExcludeTags, FilterTags (+tested both). 
Cleaned up much AzSK stuff (exclRGs, Subscription-scan stuff). 
Fixed various places to use correct [SVTMapping].

Add: FilterTags, ExcludeTags. RM:ExclRGs, etc

---

src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Organization.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/AzureDevOps/AzureDevOps.Project.json
src/AzSK.AzureDevOps/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Organization.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Project.ps1
src/AzSK.AzureDevOps/SVT/SVT.ps1

</br>
This PR contains the below changes:
- Control JSON updates
- Added positive members to detailed logs for SC-ALT control at both org and project level.
- Added new control for Audit stream.
- Added UI support to read PAT interactively. 
- Removed 5 org/project controls that needs to be revisited later.

Control JSON review, added +ve members for alt controls, PAT UI support , audit stream control

---

src/AzSK.ADO/AlertMonitoring/LogAnalytics.ps1
src/AzSK.ADO/AzSKStaging.ADO.psd1
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.AgentPool.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Build.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Organization.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Project.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Release.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.ServiceConnection.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.User.json
src/AzSK.ADO/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.ADO/Framework/Core/AzSKADOInfo/HostInfo.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Organization.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Project.ps1
src/AzSK.ADO/Framework/Helpers/Constants.ps1
src/AzSK.ADO/SVT/SVT.ps1

Control id changes + few AzSK.AzureDevOps reference updates

---

src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Build.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Project.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.Release.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/AzureDevOps/AzureDevOps.ServiceConnection.ps1
src/AzSK.AzureDevOps/Framework/Core/SVT/SVTResourceResolver.ps1

[ADO] svtresourceres refactore, svc con perf. changes, controlsetting null check in svc conn

---

src/AzSK/Framework/Core/ARMChecker/ARMCheckerStatus.ps1

</br>
ARM checker command generating blank excel if no control scanes.

ARM Checker bug fix

---

src/AzSK/Framework/Core/SVT/Services/ERvNet.ps1

Updated ERvNet locks control to check for any type of lock

---

src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

</br>
APIM control "Azure_APIManagement_AuthN_Use_AAD_for_Client_AuthN" was going into Error State due to change in API response. API is not returning the required properties.

APIM AAD Control Bug Fix

---

src/AzSK.Framework/Abstracts/SVTBase.ps1

Bug fix for checkifSubset feature of attestation

---

src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

PR comment resolved

---

src/AzSK.ADO/Framework/Models/AzSKSettings.ps1

policy setup msgs.

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/Services/VirtualMachine.ps1
src/AzSK/Framework/Helpers/SecurityCenterHelper.ps1

Updated VM controls to respect ASC assessment

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Configurations/SVT/Services/KeyVault.json
src/AzSK/Framework/Core/SVT/Services/AppService.ps1

App Servics kind functionApp,Linux changes

---

src/AzSK/Framework/Configurations/SVT/Services/APIManagement.json
src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

</br>
-  Adding support for Basic tire APIM</br>
-  Minor code changes

Adding support for Basic tire APIM

---

src/AzSK/Framework/Configurations/SVT/Services/KubernetesService.json
src/AzSK/Framework/Core/SVT/Services/KubernetesService.ps1

Updated AKS open ports control

---

src/AzSK.Framework/Helpers/ConfigOverride.ps1
src/AzSK.Framework/Managers/FeatureFlightingManager.ps1

Feature Flighting Changes moved to separate branch

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Helpers/ConfigOverride.ps1
src/AzSK.Framework/Helpers/ConfigurationHelper.ps1
src/AzSK.Framework/Helpers/RemoteReportHelper.ps1
src/AzSK.Framework/Listeners/RemoteReports/AIOrgTelemetry.ps1
src/AzSK.Framework/Managers/ConfigurationManager.ps1
src/AzSK.Framework/Managers/FeatureFlightingManager.ps1
src/AzSK.Framework/Models/Enums.ps1
src/AzSK/Framework/Core/AzSKInfo/ControlsInfo.ps1
src/AzSK/Framework/Framework.ps1

GAI Bug Fix

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/Services/AppService.ps1

Removing external redirect URLs check

---

src/AzSK/Framework/Core/SVT/Services/CDN.ps1

CDN control bug fix

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

</br>
GCA command is not working with Reader access permission. I have added minor code to handle this exception.

GCA command bug fix

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

LSAS controls

---

src/AzSK.Framework/Helpers/ActiveDirectoryHelper.ps1
src/AzSK/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SubscriptionSecurity.ps1

UCA (-RenewCertificate) Delete Old Certs

---

src/AzSK.Framework/Abstracts/CommandBase.ps1
src/AzSK.Framework/Helpers/RemoteReportHelper.ps1

</br>
1) Telemetrykey check correction 
2) Added environment variable to skip mutliple azsk module check for test harness debug mode

[ADO] Telemetrykey check correction

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1

Abdaga ado rename develop

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Listeners/RemoteReports/AIOrgTelemetry.ps1
src/AzSK.Framework/Models/SVT/SVTEvent.ps1

</br>
Send control scan time in milliseconds to telemetry in case of scan using Staging module

[ADO] Control scan time telemetry

---

src/AzSK.ADO/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK.ADO/Framework/Core/ContinuousAssurance/CAAutomation.ps1

[ADO] ICA/UCA modifications

---

src/AzSK.ADO/Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK.ADO/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.ADO/Framework/Helpers/Constants.ps1
src/AzSK.ADO/Framework/Managers/PartialScanManager.ps1
src/AzSK.Framework/Helpers/AIOrgTelemetryHelper.ps1

[ADO] Partial Commit in CA

---

src/AzSK.ADO/Framework/Configurations/AlertMonitoring/WorkbookSerializedData.json

adding file

---

src/AzSK.ADO/Framework/BugLog/AutoBugLog.ps1
src/AzSK.ADO/Framework/BugLog/BugMetaInfoProvider.ps1
src/AzSK.ADO/Framework/Core/SVT/SVTControlAttestation.ps1

msg updates

---

src/AzSK.Framework/Helpers/RemoteReportHelper.ps1
src/AzSK.Framework/Listeners/RemoteReports/AIOrgTelemetry.ps1
src/AzSK.Framework/Models/Enums.ps1

AIOrg Telemetry + RemoteReportHelper optimizations

---

src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Build.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Release.json
src/AzSK.ADO/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Release.ps1

var grp LSAS control in pipeline

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1

adding prop check if no task grp prsnt in build

---

src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Changed controlId of a control as it was clashing from another control

---

src/AzSK.ADO/Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK.ADO/Framework/Helpers/Constants.ps1

partial scan compute hash trimmed to 12 chars

---

src/AzSK.ADO/Framework/Abstracts/ADOSVTBase.ps1
src/AzSK.ADO/Framework/Managers/ControlStateExtension.ps1

[ADO] Org scan policyproj change

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

adding null check for pim roles

---

src/AzSK.ADO/Framework/Abstracts/ServicesSecurityStatus.ps1
src/AzSK.ADO/Framework/Managers/PartialScanManager.ps1

</br>
CA simulate, also error for RST/container not found.

CA simulate, also error for RST/container not found.

---

src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Organization.json
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Organization.ps1
src/AzSK.ADO/SVT/SVT.ps1

[ADO] PromptForPAT flag change

---

src/AzSK.ADO/Framework/Core/ContinuousAssurance/CAAutomation.ps1

Alt laws update

---

src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.VariableGroup.json
src/AzSK.ADO/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1
src/AzSK.ADO/Framework/Core/SVT/SVTControlAttestation.ps1

VG reco update, enable attestation for VG, rmv msg

---

src/AzSK.ADO/Framework/Managers/PartialScanManager.ps1

[ADO] UPC cicd fix

---

src/AzSK.ADO/Framework/Core/ContinuousAssurance/CAAutomation.ps1

[ADO] ScanIntervalHours not provided check

---

src/AzSK.ADO/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK.ADO/Framework/Models/AzSKSettings.ps1

</br>
ICA, UCA msg changes. Plus a fix for ProjectNames issue to resolve policy during ICA (which now uses ProjectName instead of ProjectNames as the param).

Msg changes. Plus a fix for ProjectNames issue.

---

src/AzSK.ADO/Framework/Helpers/Constants.ps1
src/AzSK.ADO/SVT/SVT.ps1

</br>
-SAA alias update, checkpoint-container name update

-SAA alias update,checkpoint-container name update

---

src/AzSK.ADO/Framework/Helpers/Constants.ps1

ado-scan-checkpoints

---

src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.AgentPool.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.ServiceConnection.json
src/AzSK.ADO/Framework/Configurations/SVT/ControlSettings.json

control json renamed - inactive svcconn & agt pool

---

src/AzSK.ADO/Framework/Abstracts/ADOSVTBase.ps1
src/AzSK.ADO/Framework/Configurations/AzSKSettings.json
src/AzSK.ADO/Framework/Helpers/Constants.ps1
src/AzSK.ADO/Framework/Managers/ControlStateExtension.ps1
src/AzSK.ADO/Framework/Models/AzSKSettings.ps1
src/AzSK.Framework/Helpers/ConfigurationHelper.ps1

[ADO]policy project and enable attestation changes

---

src/AzSK.ADO/AzSK.ADO.psm1
src/AzSK.ADO/Framework/Configurations/AzSKSettings.json
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Release.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.VariableGroup.ps1

</br>
Set-AzSKADOPolicySettings to support setting PolicyProject and EnableOrgControlAttestation.

Set-AzSKADOPolicySettings to support policyProject and oca.

---

src/AzSK.ADO/Framework/Managers/ControlStateExtension.ps1

checkattestation repo fr policy prj local settings

---

src/AzSK.ADO/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK.ADO/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK.ADO/Framework/Helpers/Constants.ps1
src/AzSK.ADO/Framework/Managers/ControlStateExtension.ps1
src/AzSK.ADO/Framework/Managers/PartialScanManager.ps1
src/AzSK.Framework/Helpers/ConfigurationHelper.ps1

[ADO] CA fixes from last sprint

---

src/AzSK.ADO/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Release.ps1
src/AzSK.ADO/SVT/SVT.ps1

</br>
Adding detailedscan flag to show full scan logs of below RBAC controls
ADO_Release_AuthZ_Grant_Min_RBAC_Access
ADO_Build_AuthZ_Grant_Min_RBAC_Access

[ADO] DetailedScan changes for RBAC controls

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Release.ps1

var grps ctrl bugfix if contrib not found in RBAC

---

src/AzSK.ADO/Framework/BugLog/AutoBugLog.ps1
src/AzSK.ADO/Framework/Configurations/ADOAttestation.json
src/AzSK.ADO/Framework/Configurations/BuildSTData.json
src/AzSK.ADO/Framework/Configurations/ReleaseSTData.json
src/AzSK.ADO/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.ADO/Framework/Configurations/ServiceTreeData.json
src/AzSK.ADO/Framework/Helpers/Constants.ps1
src/AzSK.ADO/Framework/Managers/ControlStateExtension.ps1
src/AzSK.ADO/Framework/Models/AzSKSettings.ps1

attestation orgpolicy repo changes

---

src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Build.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Organization.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Project.json

</br>
Reordering the sequence of admin count controls at org and project level.

Reordering the sequence of admin count controls

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Release.ps1
src/AzSK.Framework/Abstracts/AzSKRoot.ps1
src/AzSK.Framework/Abstracts/CommandBase.ps1

[ADO] DetailScan check

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Organization.ps1

</br>
changed the condition for detailed scan

changed the condition for detailed scan

---

src/AzSK.Framework/Abstracts/CommandBase.ps1

[ADO] DetailScan check modification

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1
src/AzSK.ADO/Framework/Core/SVT/SVTResourceResolver.ps1

[ADO] build control change, org and user resourceid

---

src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.AgentPool.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Organization.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Project.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.VariableGroup.json

added rbac in json

---

src/AzSK.ADO/Framework/Core/ContinuousAssurance/CAAutomation.ps1

[ADO] CA RG level permissions

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Release.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.VariableGroup.ps1

statedata in cred control

---

src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Build.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Organization.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Project.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.Release.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.User.json
src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.VariableGroup.json

updating control string ID for new controls

---

src/AzSK.ADO/Framework/Configurations/SVT/ControlSettings.json

Added limit settable vars at queue time controls and audit stream control to UBC

---

src/AzSK.Framework/Listeners/UserReports/WritePsConsole.ps1

[ADO] summary bug fix

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Release.ps1

[ADO] Build Release Rbac control fix

---

src/AzSK.Framework/Listeners/UserReports/WriteSummaryFile.ps1

[ADO] Revert SummaryFile

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Organization.ps1

rmved detailed info frm statedata of guestuser con

---

src/AzSK.ADO/Framework/Listeners/PartialScanHandler/PartialScanHandler.ps1

[ADO] Archive CA checkpoint file

---

src/AzSK.ADO/Framework/Managers/ControlStateExtension.ps1
src/AzSK.Framework/Helpers/ConfigurationHelper.ps1

removed references of older attestation and org policy repo

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Organization.ps1

</br>
Fixed StateData issue for guest users control

Fixed statedata issue for guest users

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

</br>
Display SPN name in GCA report

Display SPN name in GCA report

---

src/AzSK/Framework/Core/CredHygiene/CredHygieneScript.ps1

Cred Hygine bug fix

---

src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

</br>
Subscription persistent access control change

Subscription persistent access control change

---

src/AzSK.ADO/Framework/Core/SVT/SVTResourceResolver.ps1

update rsrc id for svc conn

---

src/AzSK.Framework/Listeners/RemoteReports/RemoteReportsListener.ps1

EnablePIMResourceGrouptelemetry : changed ( * ) to current sub id

---

src/AzSK/Framework/Core/SVT/Services/ERvNet.ps1

ERvNET control exemption for EventGrid resources

ERvNET control exemption for EventGrid resources

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.AgentPool.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Project.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Release.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.VariableGroup.ps1
src/AzSK.ADO/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK.ADO/Framework/Managers/ControlStateExtension.ps1
src/AzSK.Framework/Helpers/LogAnalyticsHelper.ps1

[ADO] Resourceid & respective changes, LA module name fix, attestation repo fetching tuned

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK/Framework/Configurations/SVT/SubscriptionCore/SubscriptionCore.json

changes for preventing attestation drift if applytoversionupto is *

---

src/AzSK/SVT/SVT.ps1

Bug fix for Get-AzSKExpressRouteNetworkSecurityStatus  command

---

src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Core/SVT/Services/KeyVault.ps1

</br>
Removed feature flag "EnableKeyVaultApplicationsFix"

Removed feature flag "EnableKeyVaultApplicationsFix"

---

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/OSSConfiguration/RunbookScanAgent.ps1

Scan agent changes to disable OSS CA telemetry - based on automation account variable

---

src/AzSK/AlertMonitoring/LogAnalytics.ps1
src/AzSK/Framework/Core/AzureMonitoring/LogAnalyticsMonitoring.ps1

Changes related to Install-LA soln cmd

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Organization.ps1

</br>
Fixed the bug related to attestation for control "ADO_Organization_AuthZ_Review_Inactive_User"

Fixed the attestation issue

---

src/AzSK.Framework/Helpers/ActiveDirectoryHelper.ps1
src/AzSK/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SubscriptionSecurity.ps1

Added corresponding Test case : https://microsoftit.visualstudio.com/OneITVSO/_workitems/edit/6453187

Added switch DeleteOldCredentials in UCA

---

src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/OSSConfiguration/RunbookScanAgent.ps1

fixes for null value

---

src/AzSK.ADO/Framework/Core/SVT/SVTResourceResolver.ps1

[ADO] Total svc vs Scannable svc count

---

src/AzSK/Framework/Configurations/SVT/Services/ERvNet.json
src/AzSK/Framework/Configurations/SVT/Services/VirtualMachine.json

Removing feature to prevent attestation drift for VM and ERVnet controls

---

src/AzSK.Framework/Models/ContinuousAssurance/AutomationAccount.ps1
src/AzSK/AzSK.psm1
src/AzSK/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/Continuous_Assurance_Runbook.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SubscriptionSecurity.ps1

ICA UCA changes for CA telemetry

---

src/AzSK.ADO/Framework/Core/SVT/SVTResourceResolver.ps1

corrected the variable name to store VG SVT

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Release.ps1

[ADO] secrets check in VarGrp for release & build

---

src/AzSK.ADO/Framework/Core/SVT/SVTResourceResolver.ps1

</br>
Ability to get ADO rsrc info from ADOInfo API if supported and enabled via org policy.

Support for using ADOInfoAPI if present.

---

src/AzSK.ADO/Framework/Core/SVT/SVTResourceResolver.ps1

skipping azure pipelines from scan

---

src/AzSK/Framework/Core/SVT/Services/APIManagement.ps1

APIM api version change

---

src/AzSK/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK/Framework/Abstracts/AzSVTCommandBase.ps1
src/AzSK/Framework/Configurations/ContinuousAssurance/RunbookScanAgent.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/SubscriptionSecurity/SubscriptionSecurity.ps1
src/OSSConfiguration/RunbookScanAgent.ps1

ICA UCA for UsageTelemetryLevel code review fixes

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.ServiceConnection.ps1

</br>
Fixed control error for ADO_ServiceConnection_AuthZ_Dont_Grant_Subscription_Access

[ADO] Svc control error fix : ADO_ServiceConnection_AuthZ_Dont_Grant_Subscription_Access

---

src/AzSK.ADO/Framework/Configurations/SVT/ControlSettings.json
src/AzSK.ADO/Framework/Core/SVT/SVTResourceResolver.ps1
src/AzSK.ADO/Framework/Models/AzSKSettings.ps1
src/AzSK.Framework/Helpers/ConfigurationHelper.ps1

Removed policy debug msgs plus ncluded hollow body for ADOInfoAPI

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Organization.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Project.ps1

replaced identityid with originid alt admin controls

---

src/AzSK.ADO/AzSKADOInfo/AzSKADOInfo.ps1
src/AzSK.ADO/Framework/Core/SVT/SVTResourceResolver.ps1

-saa and -svcid behavior resolution plus -ProjectNames flag in GADI

---

src/AzSK.Framework/Abstracts/SVTBase.ps1
src/AzSK.Framework/Helpers/LogAnalyticsHelper.ps1
src/AzSK.Framework/Listeners/UserReports/WriteDetailedLog.ps1
src/AzSK.Framework/Listeners/UserReports/WritePsConsole.ps1
src/AzSK.Framework/Listeners/UserReports/WriteSummaryFile.ps1
src/AzSK.Framework/Managers/AzSKPDFExtension.ps1
src/AzSK.Framework/Managers/ControlStateExtension.ps1
src/AzSK.Framework/Models/Enums.ps1
src/AzSK.Framework/Models/RemoteReports/CsvOutputModel.ps1
src/AzSK.Framework/Models/SVT/SVTConfig.ps1
src/AzSK/AlertMonitoring/LogAnalytics.ps1
src/AzSK/AzSKStaging.psd1
src/AzSK/Framework/Abstracts/AzSVTBase.ps1
src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/AzSKInfo/ControlsInfo.ps1
src/AzSK/Framework/Core/AzureMonitoring/LogAnalyticsMonitoring.ps1
src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1
src/AzSK/Framework/Core/SVT/SVTStatusReport.ps1

AzSK to AzTS migration changes

---

src/AzSK.ADO/Framework/Configurations/SVT/ADO/ADO.ServiceConnection.json
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Build.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Release.ps1

added secret to control msg

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.AgentPool.ps1

</br>
Control ADO_AgentPool_DP_Review_Inactive_Pool error fix

[ADO] Agentpool control error fix

---

src/AzSK.ADO/Framework/BugLog/BugMetaInfoProvider.ps1
src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.ServiceConnection.ps1

bug logging fix

---

src/SecureAzureDevOpsExtension/ADOSecurityScanner_Task/ADOSecurityScannerSVTRuntime.ps1
src/SecureAzureDevOpsExtension/ADOSecurityScanner_Task/task.json
src/SecureAzureDevOpsExtension/vss-extension.json

[ADO] Extension changes: svc id based scan

---

src/SecureAzureDevOpsExtension/ADOSecurityScanner_Task/task.json
src/SecureAzureDevOpsExtension/vss-extension.json

Support link update, etc.

---

src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.ServiceConnection.ps1

added passing msg for ML based svc conn

---

src/AzSK/Framework/Core/AzSKInfo/ControlsInfo.ps1

Bug fix for GAI control info policy cached

---

src/SecureAzureDevOpsExtension/ADOSecurityScanner_Task/ADOSecurityScannerSVTRuntime.ps1
src/SecureAzureDevOpsExtension/ADOSecurityScanner_Task/task.json
src/SecureAzureDevOpsExtension/vss-extension.json

Added use-TLS-version flag

---

src/AzSK/Framework/Core/SubscriptionSecurity/Alerts.ps1

</br>
Fixed bug for Set-AzSKAlert command

Fixed bug for Set-AzSKAlert command

---

src/AzSK/Framework/Configurations/SubscriptionSecurity/CredentialHygieneAlert.json
src/AzSK/Framework/Configurations/SubscriptionSecurity/CredentialHygieneAlert_CredentialGroup.json
src/AzSK/Framework/Core/CredHygiene/CredHygieneScript.ps1

Fixed Cred Hygiene bug

---

src/AzSK.Framework/Abstracts/ServicesSecurityStatus.ps1

BugFix for auto opening of scanresult folder after attestation

---

src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

bug fixes for Limit admin and CA policy controls

---

src/AzSK.Framework/Listeners/Webhook/WebhookOutput.ps1
src/AzSK/Framework/Core/SVT/Services/SQLDatabase.ps1

</br>
SQL threat detection control bug fix.

SQL threat detection control bug fix

---

src/AzSK.Framework/Managers/ControlStateExtension.ps1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/CAwithACI/ContinuousAssurance.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/Framework/Helpers/ResourceHelper.ps1

merging TLS changes into attestation changes

---

src/AzSK.Framework/Managers/ControlStateExtension.ps1
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/CAwithACI/ContinuousAssurance.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/PolicySetup/PolicySetup.ps1
src/AzSK/Framework/Helpers/ResourceHelper.ps1

Code change for updating TLS and blob settings

---

src/AzSK/AzSKStaging.psd1
src/AzSK/Framework/Configurations/FeatureFlighting.json
src/AzSK/Framework/Configurations/SVT/ControlSettings.json
src/AzSK/Framework/Core/SVT/SVTControlAttestation.ps1

Blocking attestation for migrated controls + Metadata updates

---

src/AzSK.Framework/Helpers/RemoteReportHelper.ps1
src/AzSK/ContinuousAssurance/ContinuousAssurance.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/AzSK/Framework/Core/SVT/Services/KeyVault.ps1
src/AzSK/Framework/Core/SVT/SubscriptionCore/SubscriptionCore.ps1

Clean AzSK deployed resources + other bug fixes

---

src/AzSK.Framework/Abstracts/SVTCommandBase.ps1
src/AzSK/Framework/Core/SVT/SubscriptionSecurityStatus.ps1

Fix for auto opening of scan result folder

---

src/AzSK.Framework/Listeners/UserReports/WritePsConsole.ps1
src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1
src/OSSConfiguration/AzSK.json

Text changes feedback

---

src/oss-config-staging/1.0.0/AzSK.Pre.json
src/oss-config-staging/4.16.3/ARMControls.json
src/oss-config-staging/4.16.3/AzSK.json
src/oss-config-staging/4.16.3/ControlSettings.json
src/oss-config-staging/4.16.3/ServerConfigMetadata.json

changes for 4.16.3 version

---

src/AzSK/Framework/Core/ContinuousAssurance/CAAutomation.ps1

increasing time to check resource deletion

---

README.md

Added sunset notice
